FROM maven:3.6.0-jdk-8-alpine as build

WORKDIR /app

COPY . /app

# install nodejs
RUN apk --update add nodejs npm
# install git client
RUN apk --update add git
# install bower
RUN npm install -g bower

WORKDIR game-engine.core
RUN mvn -Dmaven.test.skip=true install;
WORKDIR ../game-engine.web
RUN mkdir logs
RUN if [ -e "/app/run-configs/users.yml" ]; then cp /app/run-configs/users.yml /app/game-engine.web/src/main/resources/users.yml; fi;
RUN cd /app/game-engine.web/src/main/resources/consoleweb-assets && bower --allow-root install
RUN cd /app/game-engine.web && mvn -Dmaven.test.skip=true package

FROM openjdk:8-alpine
WORKDIR /app
#ENV JAVA_TOOL_OPTIONS="-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
COPY --from=build /app/game-engine.web/target/game-engine.web.jar /app
EXPOSE 8010
CMD java -Djava.rmi.server.hostname=localhost -Dcom.sun.management.jmxremote.port=7777 -Dcom.sun.management.jmxremote.rmi.port=7777 -Dcom.sun.management.jmxremote.authenticate=false \
-Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.local.only=false -jar game-engine.web.jar --spring.profiles.active=platform
