FROM maven:3.5.2-jdk-8-alpine

WORKDIR /app

ARG release

# install git client
RUN apk --update add git

# clone the project
RUN git clone https://github.com/smartcommunitylab/smartcampus.gamification.git gamification-engine

# install nodejs
RUN apk --update add nodejs

# install bower
RUN npm install -g bower

WORKDIR gamification-engine

#checkout release tag
RUN git checkout $release

WORKDIR game-engine.core
RUN mvn -Dmaven.test.skip=true install;
WORKDIR ../game-engine.web
RUN mkdir logs
RUN mkdir /app/run-configs

EXPOSE 8010
CMD if [ -e "/app/run-configs/users.yml" ]; then cp /app/run-configs/users.yml /app/gamification-engine/game-engine.web/src/main/resources/users.yml; fi; cd src/main/resources/consoleweb-assets && bower --allow-root install && cd /app/gamification-engine/game-engine.web && mvn -Dmaven.test.skip=true package && java -Xms512m -Xmx1024m -XX:MaxMetaspaceSize=1024m -DlogFolder=/app/gamification-engine/game-engine.web/logs -Djava.rmi.server.hostname=localhost -Dcom.sun.management.jmxremote.port=7777 -Dcom.sun.management.jmxremote.rmi.port=7777  -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.local.only=false -jar target/game-engine.web.jar --spring.profiles.active=sec --server.contextPath=/gamification --task.persistence.activate=false --mongo.host=mongodb --mongo.dbname=gamification --server.port=8010
