package eu.trentorise.game.model

import eu.trentorise.game.core.Utility;
global Utility utils;

rule "rewardAssignment"
when
    $reward : Reward() 
    $pcCalculation: PointConcept(name == ((Reward) $reward).getCalculationPointConcept().getName())
    $pcTarget : PointConcept(name == ((Reward) $reward).getTargetPointConcept().getName())

then
	Reward reward = (Reward) $reward;
	utils.log("Assigning " + reward.getTargetPointConcept().getName());
	
	//WARNING: here we are assuming that calculation point and target point belong 
	//to the same point concept, and hence, there is no need for conversion
	Double percentage = reward.getPercentage();
	
	Double base = $pcCalculation.getPeriodCurrentScore(reward.getCalculationPointConcept().getPeriod());
	Double inc = (base * percentage / 100) <= reward.getThreshold() ? (base * percentage / 100) : reward.getThreshold();
	$pcTarget.setScore($pcTarget.getScore() + inc);
			
	update($pcTarget);

end

