package eu.trentorise.game.model

import eu.trentorise.game.core.Utility;
global Utility utils;

rule "rewardAssignment"
when
    InputData($reward : data["reward"])
    $pcCalculation: PointConcept(name == ((Reward) $reward).getCalculationPointConcept().getName())
    $pcTarget : PointConcept(name == ((Reward) $reward).getTargetPointConcept().getName())

then
	Reward reward = (Reward) $reward;
	utils.log("Assigning " + reward.getTargetPointConcept().getName());
	Double percentage = reward.getPercentage();
	
	Double base = $pcCalculation.getPeriodCurrentScore(reward.getCalculationPointConcept().getPeriod());

	$pcTarget.increment(base * percentage / 100);
			
	update($pcTarget);

end

