/**
 * Copyright 2018-2019 SmartCommunity Lab(FBK-ICT).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

/*
 * Gamification Engine API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.smartcommunitylab.oauth.api;

import java.util.List;

import org.junit.Ignore;
import org.junit.Test;

import it.smartcommunitylab.ApiException;
import it.smartcommunitylab.model.PointConcept;

/**
 * API tests for DomainPointConceptControllerApi
 */
@Ignore
public class DomainPointConceptControllerApiTest {

    private final DomainPointConceptControllerApi api = new DomainPointConceptControllerApi();

    
    /**
     * Add point
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addPointUsingPOST1Test() throws ApiException {
        String domain = null;
        String gameId = null;
        PointConcept point = null;
        PointConcept response = api.addPointUsingPOST1(domain, gameId, point);

        // TODO: test validations
    }
    
    /**
     * Delete point
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deletePointUsingDELETETest() throws ApiException {
        String domain = null;
        String gameId = null;
        String pointId = null;
        api.deletePointUsingDELETE(domain, gameId, pointId);

        // TODO: test validations
    }
    
    /**
     * Get point
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void readPointUsingGETTest() throws ApiException {
        String domain = null;
        String gameId = null;
        String pointId = null;
        PointConcept response = api.readPointUsingGET(domain, gameId, pointId);

        // TODO: test validations
    }
    
    /**
     * Get points
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void readPointsUsingGET1Test() throws ApiException {
        String domain = null;
        String gameId = null;
        List<PointConcept> response = api.readPointsUsingGET1(domain, gameId);

        // TODO: test validations
    }
    
    /**
     * Edit point
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updatePointUsingPUTTest() throws ApiException {
        String domain = null;
        String gameId = null;
        PointConcept point = null;
        api.updatePointUsingPUT(domain, gameId, point);

        // TODO: test validations
    }
    
}
