/*
 * Gamification Engine API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.smartcommunitylab.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * ClassificationDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-12-12T17:12:54.525+01:00")
public class ClassificationDTO {
  @SerializedName("classificationName")
  private String classificationName = null;

  @SerializedName("gameId")
  private String gameId = null;

  @SerializedName("itemType")
  private String itemType = null;

  @SerializedName("itemsToNotificate")
  private Integer itemsToNotificate = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("type")
  private String type = null;

  public ClassificationDTO classificationName(String classificationName) {
    this.classificationName = classificationName;
    return this;
  }

   /**
   * Get classificationName
   * @return classificationName
  **/
  @ApiModelProperty(value = "")
  public String getClassificationName() {
    return classificationName;
  }

  public void setClassificationName(String classificationName) {
    this.classificationName = classificationName;
  }

  public ClassificationDTO gameId(String gameId) {
    this.gameId = gameId;
    return this;
  }

   /**
   * Get gameId
   * @return gameId
  **/
  @ApiModelProperty(value = "")
  public String getGameId() {
    return gameId;
  }

  public void setGameId(String gameId) {
    this.gameId = gameId;
  }

  public ClassificationDTO itemType(String itemType) {
    this.itemType = itemType;
    return this;
  }

   /**
   * Get itemType
   * @return itemType
  **/
  @ApiModelProperty(value = "")
  public String getItemType() {
    return itemType;
  }

  public void setItemType(String itemType) {
    this.itemType = itemType;
  }

  public ClassificationDTO itemsToNotificate(Integer itemsToNotificate) {
    this.itemsToNotificate = itemsToNotificate;
    return this;
  }

   /**
   * Get itemsToNotificate
   * @return itemsToNotificate
  **/
  @ApiModelProperty(value = "")
  public Integer getItemsToNotificate() {
    return itemsToNotificate;
  }

  public void setItemsToNotificate(Integer itemsToNotificate) {
    this.itemsToNotificate = itemsToNotificate;
  }

  public ClassificationDTO name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ClassificationDTO type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClassificationDTO classificationDTO = (ClassificationDTO) o;
    return Objects.equals(this.classificationName, classificationDTO.classificationName) &&
        Objects.equals(this.gameId, classificationDTO.gameId) &&
        Objects.equals(this.itemType, classificationDTO.itemType) &&
        Objects.equals(this.itemsToNotificate, classificationDTO.itemsToNotificate) &&
        Objects.equals(this.name, classificationDTO.name) &&
        Objects.equals(this.type, classificationDTO.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(classificationName, gameId, itemType, itemsToNotificate, name, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClassificationDTO {\n");
    
    sb.append("    classificationName: ").append(toIndentedString(classificationName)).append("\n");
    sb.append("    gameId: ").append(toIndentedString(gameId)).append("\n");
    sb.append("    itemType: ").append(toIndentedString(itemType)).append("\n");
    sb.append("    itemsToNotificate: ").append(toIndentedString(itemsToNotificate)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

