/*
 * Gamification Engine API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.smartcommunitylab.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * ComplexSearchQuery
 */

public class ComplexSearchQuery {
  @SerializedName("query")
  private Map<String, List> query = new HashMap<String, List>();

  @SerializedName("projection")
  private StructuredProjection projection = null;

  @SerializedName("sortItems")
  private List<StructuredSortItem> sortItems = new ArrayList<StructuredSortItem>();

  public ComplexSearchQuery query(Map<String, List> query) {
    this.query = query;
    return this;
  }

  public ComplexSearchQuery putQueryItem(String key, List queryItem) {
    this.query.put(key, queryItem);
    return this;
  }

   /**
   * Get query
   * @return query
  **/
  @ApiModelProperty(required = true, value = "")
  public Map<String, List> getQuery() {
    return query;
  }

  public void setQuery(Map<String, List> query) {
    this.query = query;
  }

  public ComplexSearchQuery projection(StructuredProjection projection) {
    this.projection = projection;
    return this;
  }

   /**
   * Get projection
   * @return projection
  **/
  @ApiModelProperty(required = true, value = "")
  public StructuredProjection getProjection() {
    return projection;
  }

  public void setProjection(StructuredProjection projection) {
    this.projection = projection;
  }

  public ComplexSearchQuery sortItems(List<StructuredSortItem> sortItems) {
    this.sortItems = sortItems;
    return this;
  }

  public ComplexSearchQuery addSortItemsItem(StructuredSortItem sortItemsItem) {
    this.sortItems.add(sortItemsItem);
    return this;
  }

   /**
   * Get sortItems
   * @return sortItems
  **/
  @ApiModelProperty(required = true, value = "")
  public List<StructuredSortItem> getSortItems() {
    return sortItems;
  }

  public void setSortItems(List<StructuredSortItem> sortItems) {
    this.sortItems = sortItems;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComplexSearchQuery complexSearchQuery = (ComplexSearchQuery) o;
    return Objects.equals(this.query, complexSearchQuery.query) &&
        Objects.equals(this.projection, complexSearchQuery.projection) &&
        Objects.equals(this.sortItems, complexSearchQuery.sortItems);
  }

  @Override
  public int hashCode() {
    return Objects.hash(query, projection, sortItems);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComplexSearchQuery {\n");
    
    sb.append("    query: ").append(toIndentedString(query)).append("\n");
    sb.append("    projection: ").append(toIndentedString(projection)).append("\n");
    sb.append("    sortItems: ").append(toIndentedString(sortItems)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

