/*
 * Gamification Engine API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.smartcommunitylab.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * Config
 */

public class Config {
  @SerializedName("availableModels")
  private List<String> availableModels = null;

  @SerializedName("choices")
  private Integer choices = null;

  public Config availableModels(List<String> availableModels) {
    this.availableModels = availableModels;
    return this;
  }

  public Config addAvailableModelsItem(String availableModelsItem) {
    if (this.availableModels == null) {
      this.availableModels = new ArrayList<String>();
    }
    this.availableModels.add(availableModelsItem);
    return this;
  }

   /**
   * Get availableModels
   * @return availableModels
  **/
  @ApiModelProperty(value = "")
  public List<String> getAvailableModels() {
    return availableModels;
  }

  public void setAvailableModels(List<String> availableModels) {
    this.availableModels = availableModels;
  }

  public Config choices(Integer choices) {
    this.choices = choices;
    return this;
  }

   /**
   * Get choices
   * @return choices
  **/
  @ApiModelProperty(value = "")
  public Integer getChoices() {
    return choices;
  }

  public void setChoices(Integer choices) {
    this.choices = choices;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Config config = (Config) o;
    return Objects.equals(this.availableModels, config.availableModels) &&
        Objects.equals(this.choices, config.choices);
  }

  @Override
  public int hashCode() {
    return Objects.hash(availableModels, choices);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Config {\n");
    
    sb.append("    availableModels: ").append(toIndentedString(availableModels)).append("\n");
    sb.append("    choices: ").append(toIndentedString(choices)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

