///**
// * Copyright 2018-2019 SmartCommunity Lab(FBK-ICT).
// *
// * Licensed under the Apache License, Version 2.0 (the "License");
// * you may not use this file except in compliance with the License.
// * You may obtain a copy of the License at
// *
// *     http://www.apache.org/licenses/LICENSE-2.0
// *
// * Unless required by applicable law or agreed to in writing, software
// * distributed under the License is distributed on an "AS IS" BASIS,
// * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// * See the License for the specific language governing permissions and
// * limitations under the License.
// *
// */
//
///*
// * Gamification Engine API
// * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
// *
// * OpenAPI spec version: v1.0
// * 
// *
// * NOTE: This class is auto generated by the swagger code generator program.
// * https://github.com/swagger-api/swagger-codegen.git
// * Do not edit the class manually.
// */
//
//package it.smartcommunitylab.model;
//
//import java.util.Map;
//import java.util.Objects;
//
//import com.google.gson.annotations.SerializedName;
//
//import io.swagger.annotations.ApiModelProperty;
//
///**
// * GameConcept
// */
//
//public class GameConcept {
//	@SerializedName("id")
//	protected String id = null;
//
//	@SerializedName("name")
//	protected String name = null;
//
//	public GameConcept(String name) {
//		this.name = name;
//	}
//
//	public GameConcept() {
//	}
//
//	public GameConcept(Map<String, Object> jsonProps) {
//		if (jsonProps != null) {
//			Object idField = jsonProps.get("id");
//			id = (idField != null) ? String.valueOf(idField) : null;
//			name = (String) jsonProps.get("name");
//		}
//	}
//
//	/**
//	 * Get id
//	 * 
//	 * @return id
//	 **/
//	@ApiModelProperty(value = "")
//	public String getId() {
//		return id;
//	}
//
//	public void setId(String id) {
//		this.id = id;
//	}
//
//	public GameConcept name(String name) {
//		this.name = name;
//		return this;
//	}
//
//	/**
//	 * Get name
//	 * 
//	 * @return name
//	 **/
//	@ApiModelProperty(value = "")
//	public String getName() {
//		return name;
//	}
//
//	public void setName(String name) {
//		this.name = name;
//	}
//
//	@Override
//	public boolean equals(java.lang.Object o) {
//		if (this == o) {
//			return true;
//		}
//		if (o == null || getClass() != o.getClass()) {
//			return false;
//		}
//		GameConcept gameConcept = (GameConcept) o;
//		return Objects.equals(this.id, gameConcept.id) && Objects.equals(this.name, gameConcept.name);
//	}
//
//	@Override
//	public int hashCode() {
//		return Objects.hash(id, name);
//	}
//
//	@Override
//	public String toString() {
//		StringBuilder sb = new StringBuilder();
//		sb.append("class GameConcept {\n");
//
//		sb.append("    id: ").append(toIndentedString(id)).append("\n");
//		sb.append("    name: ").append(toIndentedString(name)).append("\n");
//		sb.append("}");
//		return sb.toString();
//	}
//
//	/**
//	 * Convert the given object to string with each line indented by 4 spaces
//	 * (except the first line).
//	 */
//	private String toIndentedString(java.lang.Object o) {
//		if (o == null) {
//			return "null";
//		}
//		return o.toString().replace("\n", "\n    ");
//	}
//
//}
