/**
 * Copyright 2018-2019 SmartCommunity Lab(FBK-ICT).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

/*
 * Gamification Engine API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.smartcommunitylab.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * GeneralClassificationDTO
 */

public class GeneralClassificationDTO {
  @SerializedName("classificationName")
  private String classificationName = null;

  @SerializedName("cronExpression")
  private String cronExpression = null;

  @SerializedName("gameId")
  private String gameId = null;

  @SerializedName("itemType")
  private String itemType = null;

  @SerializedName("itemsToNotificate")
  private Integer itemsToNotificate = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("type")
  private String type = null;

  public GeneralClassificationDTO classificationName(String classificationName) {
    this.classificationName = classificationName;
    return this;
  }

   /**
   * Get classificationName
   * @return classificationName
  **/
  @ApiModelProperty(value = "")
  public String getClassificationName() {
    return classificationName;
  }

  public void setClassificationName(String classificationName) {
    this.classificationName = classificationName;
  }

  public GeneralClassificationDTO cronExpression(String cronExpression) {
    this.cronExpression = cronExpression;
    return this;
  }

   /**
   * Get cronExpression
   * @return cronExpression
  **/
  @ApiModelProperty(value = "")
  public String getCronExpression() {
    return cronExpression;
  }

  public void setCronExpression(String cronExpression) {
    this.cronExpression = cronExpression;
  }

  public GeneralClassificationDTO gameId(String gameId) {
    this.gameId = gameId;
    return this;
  }

   /**
   * Get gameId
   * @return gameId
  **/
  @ApiModelProperty(value = "")
  public String getGameId() {
    return gameId;
  }

  public void setGameId(String gameId) {
    this.gameId = gameId;
  }

  public GeneralClassificationDTO itemType(String itemType) {
    this.itemType = itemType;
    return this;
  }

   /**
   * Get itemType
   * @return itemType
  **/
  @ApiModelProperty(value = "")
  public String getItemType() {
    return itemType;
  }

  public void setItemType(String itemType) {
    this.itemType = itemType;
  }

  public GeneralClassificationDTO itemsToNotificate(Integer itemsToNotificate) {
    this.itemsToNotificate = itemsToNotificate;
    return this;
  }

   /**
   * Get itemsToNotificate
   * @return itemsToNotificate
  **/
  @ApiModelProperty(value = "")
  public Integer getItemsToNotificate() {
    return itemsToNotificate;
  }

  public void setItemsToNotificate(Integer itemsToNotificate) {
    this.itemsToNotificate = itemsToNotificate;
  }

  public GeneralClassificationDTO name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public GeneralClassificationDTO type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GeneralClassificationDTO generalClassificationDTO = (GeneralClassificationDTO) o;
    return Objects.equals(this.classificationName, generalClassificationDTO.classificationName) &&
        Objects.equals(this.cronExpression, generalClassificationDTO.cronExpression) &&
        Objects.equals(this.gameId, generalClassificationDTO.gameId) &&
        Objects.equals(this.itemType, generalClassificationDTO.itemType) &&
        Objects.equals(this.itemsToNotificate, generalClassificationDTO.itemsToNotificate) &&
        Objects.equals(this.name, generalClassificationDTO.name) &&
        Objects.equals(this.type, generalClassificationDTO.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(classificationName, cronExpression, gameId, itemType, itemsToNotificate, name, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GeneralClassificationDTO {\n");
    
    sb.append("    classificationName: ").append(toIndentedString(classificationName)).append("\n");
    sb.append("    cronExpression: ").append(toIndentedString(cronExpression)).append("\n");
    sb.append("    gameId: ").append(toIndentedString(gameId)).append("\n");
    sb.append("    itemType: ").append(toIndentedString(itemType)).append("\n");
    sb.append("    itemsToNotificate: ").append(toIndentedString(itemsToNotificate)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

