/*
 * Gamification Engine API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.smartcommunitylab.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * RawSearchQuery
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-12-12T17:12:54.525+01:00")
public class RawSearchQuery {
  @SerializedName("query")
  private Object query = null;

  @SerializedName("projection")
  private Projection projection = null;

  @SerializedName("sortItems")
  private List<SortItem> sortItems = new ArrayList<SortItem>();

  public RawSearchQuery query(Object query) {
    this.query = query;
    return this;
  }

   /**
   * Get query
   * @return query
  **/
  @ApiModelProperty(required = true, value = "")
  public Object getQuery() {
    return query;
  }

  public void setQuery(Object query) {
    this.query = query;
  }

  public RawSearchQuery projection(Projection projection) {
    this.projection = projection;
    return this;
  }

   /**
   * Get projection
   * @return projection
  **/
  @ApiModelProperty(required = true, value = "")
  public Projection getProjection() {
    return projection;
  }

  public void setProjection(Projection projection) {
    this.projection = projection;
  }

  public RawSearchQuery sortItems(List<SortItem> sortItems) {
    this.sortItems = sortItems;
    return this;
  }

  public RawSearchQuery addSortItemsItem(SortItem sortItemsItem) {
    this.sortItems.add(sortItemsItem);
    return this;
  }

   /**
   * Get sortItems
   * @return sortItems
  **/
  @ApiModelProperty(required = true, value = "")
  public List<SortItem> getSortItems() {
    return sortItems;
  }

  public void setSortItems(List<SortItem> sortItems) {
    this.sortItems = sortItems;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RawSearchQuery rawSearchQuery = (RawSearchQuery) o;
    return Objects.equals(this.query, rawSearchQuery.query) &&
        Objects.equals(this.projection, rawSearchQuery.projection) &&
        Objects.equals(this.sortItems, rawSearchQuery.sortItems);
  }

  @Override
  public int hashCode() {
    return Objects.hash(query, projection, sortItems);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RawSearchQuery {\n");
    
    sb.append("    query: ").append(toIndentedString(query)).append("\n");
    sb.append("    projection: ").append(toIndentedString(projection)).append("\n");
    sb.append("    sortItems: ").append(toIndentedString(sortItems)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

