/*
 * Gamification Engine API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.smartcommunitylab.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * WrapperQuery
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-12-12T17:12:54.525+01:00")
public class WrapperQuery {
  @SerializedName("complexQuery")
  private ComplexSearchQuery complexQuery = null;

  @SerializedName("rawQuery")
  private RawSearchQuery rawQuery = null;

  public WrapperQuery complexQuery(ComplexSearchQuery complexQuery) {
    this.complexQuery = complexQuery;
    return this;
  }

   /**
   * Get complexQuery
   * @return complexQuery
  **/
  @ApiModelProperty(value = "")
  public ComplexSearchQuery getComplexQuery() {
    return complexQuery;
  }

  public void setComplexQuery(ComplexSearchQuery complexQuery) {
    this.complexQuery = complexQuery;
  }

  public WrapperQuery rawQuery(RawSearchQuery rawQuery) {
    this.rawQuery = rawQuery;
    return this;
  }

   /**
   * Get rawQuery
   * @return rawQuery
  **/
  @ApiModelProperty(value = "")
  public RawSearchQuery getRawQuery() {
    return rawQuery;
  }

  public void setRawQuery(RawSearchQuery rawQuery) {
    this.rawQuery = rawQuery;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WrapperQuery wrapperQuery = (WrapperQuery) o;
    return Objects.equals(this.complexQuery, wrapperQuery.complexQuery) &&
        Objects.equals(this.rawQuery, wrapperQuery.rawQuery);
  }

  @Override
  public int hashCode() {
    return Objects.hash(complexQuery, rawQuery);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WrapperQuery {\n");
    
    sb.append("    complexQuery: ").append(toIndentedString(complexQuery)).append("\n");
    sb.append("    rawQuery: ").append(toIndentedString(rawQuery)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

