package eu.trentorise.game.model

import eu.trentorise.game.notification.BadgeNotification;

import eu.trentorise.game.core.Utility;

global Utility utils;

rule "10 point pr badge"
	salience -1000
when
    PointConcept(name == 'p+r', score >= 10.0)
    $bc : BadgeCollectionConcept(name == "p+r", badgeEarned not contains '10-point-pr')
    Game( $gameId: id)
    Player( $playerId : id)
then
	utils.log("apply \'10-point-pr badge\'");
	$bc.getBadgeEarned().add('10-point-pr');
	insert( new BadgeNotification($gameId,$playerId,'10-point-pr'));
	update( $bc );
end

rule "20 point pr badge"
	salience -1000
when
    PointConcept(name == 'p+r', score >= 20.0)
    $bc : BadgeCollectionConcept(name == "p+r", badgeEarned not contains '20-point-pr')
    Game( $gameId: id)
    Player( $playerId : id)
then
	utils.log("apply \'20-point-pr badge\'");
	$bc.getBadgeEarned().add('20-point-pr');
	insert( new BadgeNotification($gameId,$playerId,'20-point-pr'));
	update( $bc );
end


rule "50 point pr badge"
	salience -1000
when
    PointConcept(name == 'p+r', score >= 50.0)
    $bc : BadgeCollectionConcept(name == "p+r", badgeEarned not contains '50-point-pr')
    Game( $gameId: id)
    Player( $playerId : id)
then
	utils.log("apply \'50-point-pr badge\'");
	$bc.getBadgeEarned().add('50-point-pr');
	insert( new BadgeNotification($gameId,$playerId,'50-point-pr'));
	update( $bc );
end

rule "100 point pr badge"
	salience -1000
when
    PointConcept(name == 'p+r', score >= 100.0)
    $bc : BadgeCollectionConcept(name == "p+r", badgeEarned not contains '100-point-pr')
    Game( $gameId: id)
    Player( $playerId : id)
then
	utils.log("apply \'100-point-pr badge\'");
	$bc.getBadgeEarned().add('100-point-pr');
	insert( new BadgeNotification($gameId,$playerId,'100-point-pr'));
	update( $bc );
end

rule "200 point pr badge"
	salience -1000
when
    PointConcept(name == 'p+r', score >= 200.0)
    $bc : BadgeCollectionConcept(name == "p+r", badgeEarned not contains '200-point-pr')
    Game( $gameId: id)
    Player( $playerId : id)
then
	utils.log("apply \'200-point-pr badge\'");
	$bc.getBadgeEarned().add('200-point-pr');
	insert( new BadgeNotification($gameId,$playerId,'200-point-pr'));
	update( $bc );
end