package eu.trentorise.game.model


global Integer health_walk_points;
global Integer health_bike_points;

rule "update health points"
when
    InputData( $bike : data["bikeDistance"], $walk : data["walkDistance"])
    $pc : PointConcept(name == "health")
then
	log("apply \'update health points\'");
	Double bike = $bike != null ? (Double) $bike : 0;
	Double walk = $walk != null ? (Double) $walk : 0;

	Long dist1 = Math.round(walk);
	Long dist2 = Math.round(bike);
    
    $pc.setScore($pc.getScore() + health_walk_points * dist1 + health_bike_points * dist2);
    update($pc);
end
