/*
 * Gamification Engine API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.smartcommunitylab.api;

import java.util.List;

import org.junit.Ignore;
import org.junit.Test;

import it.smartcommunitylab.ApiException;
import it.smartcommunitylab.model.Collectionstring;
import it.smartcommunitylab.model.TeamDTO;

/**
 * API tests for TeamControllerApi
 */
@Ignore
public class TeamControllerApiTest {

    private final TeamControllerApi api = new TeamControllerApi();

    
    /**
     * Add team member
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addTeamMemberUsingPUTTest() throws ApiException {
        String gameId = null;
        String teamId = null;
        String playerId = null;
        List<String> members = null;
        api.addTeamMemberUsingPUT(gameId, teamId, playerId, members);

        // TODO: test validations
    }
    
    /**
     * Create team
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createTeamUsingPOST1Test() throws ApiException {
        String gameId = null;
        TeamDTO team = null;
        api.createTeamUsingPOST1(gameId, team);

        // TODO: test validations
    }
    
    /**
     * Delte team
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteTeamUsingDELETE1Test() throws ApiException {
        String gameId = null;
        String teamId = null;
        api.deleteTeamUsingDELETE1(gameId, teamId);

        // TODO: test validations
    }
    
    /**
     * Get team members
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void readTeamMembersUsingGETTest() throws ApiException {
        String gameId = null;
        String teamId = null;
        Collectionstring response = api.readTeamMembersUsingGET(gameId, teamId);

        // TODO: test validations
    }
    
    /**
     * Delete team member
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void removeTeamMemberUsingDELETETest() throws ApiException {
        String gameId = null;
        String teamId = null;
        String playerId = null;
        List<String> members = null;
        api.removeTeamMemberUsingDELETE(gameId, teamId, playerId, members);

        // TODO: test validations
    }
    
    /**
     * Edit team
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateTeamMembersUsingPUTTest() throws ApiException {
        String gameId = null;
        String teamId = null;
        List<String> members = null;
        api.updateTeamMembersUsingPUT(gameId, teamId, members);

        // TODO: test validations
    }
    
}
