package eu.trentorise.game.model


// CH1variant - Aumenta del 15% i km fatti a piedi e avrai 50 punti bonus

/*
 CustomData to have   []=used by
    ID is a unique string that identifies the challenge instance
    
  - ch_ID_startChTs [rule] [presentation]
  - ch_ID_endChTs [rule] [presentation]
  - ch_ID_Km_traveled_during_challenge [rule] [presentation]
  - ch_ID_target [rule] [presentation]
  - ch_ID_bonus [presentation]
  - ch_ID_type [presentation]
  - ch_ID_point_type [presentation] type of bonus point -> it must contain the name of PointConcept ("green leaves" for example)
  - ch_ID_success [rule] [presentation]
  - ch_ID_mode [presentation] modality of trip [values allowed: walk, bike, bikesharing, train, bus, car]
*/
rule 'ch_ID_trace'
no-loop
when
	InputData($distance : data["walkDistance"] != null)
	$c : CustomData($now : System.currentTimeMillis(), this['ch_ID_startChTs'] <= $now, this['ch_ID_endChTs'] > $now, $counter : this['ch_ID_Km_walked_during_challenge'])
	Player(id == 'bruce_wayne') 
then

	if($counter == null) {
		$c.put('ch_ID_Km_traveled_during_challenge',(Double) $distance);	
	}else {
		$c.put('ch_ID_Km_traveled_during_challenge', (Double) $counter + (Double) $distance);
	}
	log('ch_ID update');
	update($c); 
end

rule 'ch_ID_check'
when
	Player(id == 'bruce_wayne')
	$c : CustomData($now : System.currentTimeMillis(), this['ch_ID_startChTs'] <= $now, this['ch_ID_endChTs'] > $now, this['ch_ID_Km_traveled_during_challenge'] >= this['ch_ID_target'], this['ch_ID_success'] == false)
	$pc : PointConcept(name == "green leaves")
then
	$pc.setScore($pc.getScore() + (Integer) $c.get("ch_ID_bonus"));
	$c.put('ch_ID_success',true);
	log('ch_ID success');
	update($pc); 
end