package eu.trentorise.game.model


// CH3 - Fai almeno 3 viaggi con il Bike sharing e vinci un bonus di 50 Green Points
/*
 CustomData to have   []=used by
    ID is a unique string that identifies the challenge instance
  
  - ch-ID-startChTs [rule] [presentation]
  - ch-ID-endChTs [rule] [presentation]
  - ch-ID-bonus [presentation]
  - ch-ID-type [presentation]
  - ch-ID-counter [rule] [presentation]
  - ch-ID-target [rule] [presentation]
  - ch-ID-success [rule] [presentation]
*/
rule 'ch-ID-trace'
no-loop
when
	InputData(data['bikesharing'] == true)
	$c : CustomData($now : System.currentTimeMillis(), this['ch-ID-startChTs'] <= $now, this['ch-ID-endChTs'] > $now, $counter : this['ch-ID-counter'])
	$pc : PointConcept(name == "green leaves")
	Player(id == 'dick_grayson') 
then
	log('ch-ID trace');
	if($counter == null) {
		$c.put("ch-ID-counter", 1);
	} else {
		$c.put("ch-ID-counter", (Integer) $counter + 1);
	}
	update($c); 
end

rule 'ch-ID-check'
when
	$c : CustomData($now : System.currentTimeMillis(), this['ch-ID-startChTs'] <= $now, this['ch-ID-endChTs'] > $now, this['ch-ID-counter'] == this['ch-ID-target'])
	$pc : PointConcept(name == "green leaves")
	Player(id == 'dick_grayson') 
then
	$pc.setScore($pc.getScore() + 50);
	$c.put('ch-ID-success',true);
	log('ch-ID success');
	update($pc); 
end