package eu.trentorise.game.model


// CH3 - Fai almeno 3 viaggi con il Bike sharing e vinci un bonus di 50 Green Points
/*
 CustomData to have   []=used by
    ID is a unique string that identifies the challenge instance
  
  - ch_ID_startChTs [rule] [presentation]
  - ch_ID_endChTs [rule] [presentation]
  - ch_ID_bonus [presentation]
  - ch_ID_type [presentation]
  - ch_ID_counter [rule] [presentation]
  - ch_ID_target [rule] [presentation]
  - ch_ID_success [rule] [presentation]
  - ch_ID_point_type [presentation] type of bonus point -> it must contain the name of PointConcept ("green leaves" for example)
*/
rule 'ch_ID_trace'
no-loop
when
	InputData(data['bikesharing'] == true)
	$c : CustomData($now : System.currentTimeMillis(), this['ch_ID_startChTs'] <= $now, this['ch_ID_endChTs'] > $now, $counter : this['ch_ID_counter'])
	$pc : PointConcept(name == "green leaves")
	Player(id == 'dick_grayson') 
then
	log('ch_ID trace');
	if($counter == null) {
		$c.put("ch_ID_counter", 1);
	} else {
		$c.put("ch_ID_counter", (Integer) $counter + 1);
	}
	update($c); 
end

rule 'ch_ID_check'
when
	$c : CustomData($now : System.currentTimeMillis(), this['ch_ID_startChTs'] <= $now, this['ch_ID_endChTs'] > $now, this['ch_ID_counter'] == this['ch_ID_target'])
	$pc : PointConcept(name == "green leaves")
	Player(id == 'dick_grayson') 
then
	$pc.setScore($pc.getScore() + (Integer) $c.get("ch_ID_bonus"));
	$c.put('ch_ID_success',true);
	log('ch_ID success');
	update($pc); 
end