package eu.trentorise.game.model


// CH3 - Fai almeno un viaggio con il Bike sharing e vinci un bonus di 50 Green Points
/*
 CustomData to have   []=used by
    ID is a unique string that identifies the challenge instance
  
  - ch-ID-startChTs [rule] [presentation]
  - ch-ID-endChTs [rule] [presentation]
  - ch-ID-bonus [presentation]
  - ch-ID-type [presentation]
  - ch-ID-success [rule] [presentation]
*/
rule 'ch-ID'
when
	InputData(data['bikesharing'] == true)
	$c : CustomData($now : System.currentTimeMillis(), this['ch-ID-startChTs'] <= $now, this['ch-ID-endChTs'] > $now, this['ch-ID-success'] == null)
	$pc : PointConcept(name == "green leaves")
	Player(id == 'dick_grayson') 
then
	$pc.setScore($pc.getScore() + 50);
	$c.put('ch-ID-success',true);
	log('ch-ID success');
	update($pc); 
end