package eu.trentorise.game.model

// CH7variant - completa una Badge Collection e vinci un bonus di 50 Green Points
/*
 CustomData to have   []=used by
    ID is a unique string that identifies the challenge instance
  
  - ch_ID_startChTs [rule] [presentation]
  - ch_ID_endChTs [rule] [presentation]
  - ch_ID_bonus [presentation]
  - ch_ID_type [presentation]
  - ch_ID_target [rule] [presentation]
  - ch_ID_success [rule] [presentation]
  - ch_ID_point_type [presentation] type of bonus point -> it must contain the name of PointConcept ("green leaves" for example)
*/
rule 'ch_ID'
when
	$c : CustomData($now : System.currentTimeMillis(), this['ch_ID_startChTs'] <= $now, this['ch_ID_endChTs'] > $now, $final_badge: this['ch_ID_target'], this['ch_ID_success'] == false)
	Player(id == 'jason_todd')
	BadgeCollectionConcept(name == "green leaves", badgeEarned contains $final_badge) 
	$pc : PointConcept(name == "green leaves")
then
	$pc.setScore($pc.getScore() + (Integer) $c.get("ch_ID_bonus"));
	$c.put("ch_ID_success",true);
	log('ch_ID success');
	update($pc); 
end