package eu.trentorise.game.model

// CH7variant - completa una Badge Collection e vinci un bonus di 50 Green Points
/*
 CustomData to have   []=used by
    ID is a unique string that identifies the challenge instance
  
  - ch-ID-startChTs [rule] [presentation]
  - ch-ID-endChTs [rule] [presentation]
  - ch-ID-bonus [presentation]
  - ch-ID-type [presentation]
  - ch-ID-target [rule] [presentation]
*/
rule 'ch-ID'
when
	CustomData($now: System.currentTimeMillis(), this['ch-ID-startChTs'] <= $now, this['ch-ID-endChTs'] > $now, $final_badge: this['ch-ID-target'])
	Player(id == 'jason_todd')
	BadgeCollectionConcept(name == "green leaves", badgeEarned contains $final_badge) 
	$pc : PointConcept(name == "green leaves")
then
	$pc.setScore($pc.getScore() + 50);
	log('ch-ID success');
	update($pc); 
end