package eu.trentorise.game.model


// CH9variant - raccomanda la App (il gioco?) ad almeno 10 utenti e guadagni di 50 Green Points
/*
 CustomData to have   []=used by
    ID is a unique string that identifies the challenge instance
  
  - ch_ID_startChTs [rule] [presentation]
  - ch_ID_endChTs [rule] [presentation]
  - ch_ID_recommendations_sent_during_challenges [rule] [presentation]
  - ch_ID_target [rule] [presentation]
  - ch_ID_bonus [presentation]
  - ch_ID_type [presentation]
  - ch_ID_success [rule] [presentation]
  - ch_ID_point_type [presentation] type of bonus point -> it must contain the name of PointConcept ("green leaves" for example)
  
*/
rule 'ch_ID_trace'
no-loop
when
	Action(id == 'app_sent_recommendation')
	$c : CustomData($now : System.currentTimeMillis(), this['ch_ID_startChTs'] <= $now, this['ch_ID_endChTs'] > $now, $counter : this['ch_ID_recommendations_sent_during_challenges'])
	Player(id == 'damian_wayne') 
then
	if($counter == null) {
		$c.put("ch_ID_recommendations_sent_during_challenges", 1);
	} else { 
		$c.put("ch_ID_recommendations_sent_during_challenges", (Integer) $counter + 1);
	}
	log('ch_ID trace');
	update($c);
end

rule 'ch_ID_check'
when
	Player(id == 'damian_wayne')
	$c : CustomData($now : System.currentTimeMillis(), this['ch_ID_startChTs'] <= $now, this['ch_ID_endChTs'] > $now, this['ch_ID_recommendations_sent_during_challenges'] >= this['ch_ID_target'], this['ch_ID_success'] == false)
	$pc : PointConcept(name == 'green leaves')
then
	$pc.setScore($pc.getScore() + (Integer) $c.get("ch_ID_bonus"));
	log('ch_ID success');
	$c.put("ch_ID_success",true);
	update($pc); 
end