package eu.trentorise.game.model

global Integer green_walk_bike_points;
global Integer green_bus_train_points;
global Integer green_pr_bonus;
global Integer green_sustainable_bonus;

rule "update green points"
when
    InputData( $bike : data["bikeDistance"], $walk : data["walkDistance"], $bus : data["busDistance"],$train : data["trainDistance"])
    $pc : PointConcept(name == "green leaves")
    Player($player: id)
then
	log("apply \'update green points\'");
	Double bike = $bike != null ? (Double) $bike : 0;
	Double walk = $walk != null ? (Double) $walk : 0;
    Double bus = $bus != null ? (Double) $bus : 0;
    Double train = $train != null ? (Double) $train : 0;

	Long dist1 = Math.round(bike + walk);
	//log("dist1 " + dist1);
	Long dist2 = Math.round(bus + train);
    //log("dist2 " + dist2);
    
    $pc.setScore($pc.getScore() + green_walk_bike_points * dist1 + green_bus_train_points * dist2);
    update($pc);
end