package eu.trentorise.game.model

import eu.trentorise.game.notification.BadgeNotification;

rule "10 point green badge"
	salience -1000
when
    PointConcept(name == 'green leaves', score >= 10.0)
    $bc : BadgeCollectionConcept(name == "green leaves", badgeEarned not contains '10-point-green')
    Game( $gameId: id)
    Player( $playerId : id)
then
	log("apply \'10-point-green badge\'");
	$bc.getBadgeEarned().add('10-point-green');
	insert( new BadgeNotification($gameId,$playerId,'10-point-green'));
	update( $bc );
end

rule "50 point green badge"
	salience -1000
when
    PointConcept(name == 'green leaves', score >= 50.0)
    $bc : BadgeCollectionConcept(name == 'green leaves', badgeEarned not contains '50-point-green')
    Game( $gameId: id)
    Player( $playerId : id)
then
	log("apply \'50-point-green badge\'");
	$bc.getBadgeEarned().add('50-point-green');
	insert(new BadgeNotification($gameId,$playerId,'50-point-green'));
	update( $bc );
end
