$axure.loadCurrentPage({
  "url":"points_customization.html",
  "generationDate":new Date(1401287476365.35),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"344e46f3c26c4b98b3e6f7134c2e5d98",
    "type":"Axure:Page",
    "name":"Points customization",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"41810afb3ba94e909d3ffca3f01892cb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"17px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":193,
              "y":14},
            "size":{
              "width":350,
              "height":21},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3024f4d8af974ff1a8b43881c90f9d42",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"17px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":193,
                  "y":14},
                "size":{
                  "width":350,
                  "height":21},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"72a448fc11b642bbaf45b433f54848e0",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":193,
              "y":264},
            "size":{
              "width":214,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"9f82b39877a541b68947ed42b6d14bba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"17px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":193,
              "y":237},
            "size":{
              "width":350,
              "height":21},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43f72c25a65540508b403d9c725dfe5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"17px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":193,
                  "y":237},
                "size":{
                  "width":350,
                  "height":21},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d7879956e5e44af7bd99cf644e3ba540",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"17px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":193,
              "y":184},
            "size":{
              "width":350,
              "height":21},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a197f19f0fc844c5b73f976397c41a26",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"17px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":193,
                  "y":184},
                "size":{
                  "width":350,
                  "height":21},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"26b5fe5a087b44b1b7d253e5862c7c7f",
          "label":"text field",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":193,
              "y":207},
            "size":{
              "width":214,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onFocus":{
              "description":"OnFocus",
              "cases":[{
                  "description":"Case 1<br> (If text on text field equals &quot;Search ConeTrees.com&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetWidgetText",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["26b5fe5a087b44b1b7d253e5862c7c7f"]}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"Search ConeTrees.com",
                      "stos":[]}},
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set text on text field equal to &quot;&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetFormText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["26b5fe5a087b44b1b7d253e5862c7c7f"]},
{
                                "exprType":"stringLiteral",
                                "value":"",
                                "stos":[]}]}]}}]}]},
            "onLostFocus":{
              "description":"OnLostFocus",
              "cases":[{
                  "description":"Case 1<br> (If text on text field equals &quot;&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetWidgetText",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["26b5fe5a087b44b1b7d253e5862c7c7f"]}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"",
                      "stos":[]}},
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set text on text field equal to &quot;Search ConeTrees.com&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetFormText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["26b5fe5a087b44b1b7d253e5862c7c7f"]},
{
                                "exprType":"stringLiteral",
                                "value":"Search ConeTrees.com",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true},
{
          "id":"2c92bc85cc674b61bbd4f32d64354bf8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF4342A9},
{
                  "color":0xFF4342A9},
{
                  "color":0xFF4342A9},
{
                  "color":0xFF12167E},
{
                  "color":0xFF12167E}]},
            "location":{
              "x":193,
              "y":304},
            "size":{
              "width":77,
              "height":28},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f6f3ac9b15e4b15b94b3a20eee7c6cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF4342A9},
{
                      "color":0xFF4342A9},
{
                      "color":0xFF4342A9},
{
                      "color":0xFF12167E},
{
                      "color":0xFF12167E}]},
                "location":{
                  "x":193,
                  "y":304},
                "size":{
                  "width":77,
                  "height":28},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set Check_ok to State2 show if hidden",
                      "panelsToStates":[{
                          "panelPath":["b927cc8c05bc4c7d8a97ec3aa6a9904c"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":true,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/points_customization/u8.png"}},
{
          "id":"b927cc8c05bc4c7d8a97ec3aa6a9904c",
          "label":"Check_ok",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":304},
            "size":{
              "width":24,
              "height":29}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"1388be5da4ca4bf4b377256d58a52d0a",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"964000c7dce2404c98333c353d543c0f",
              "label":"State2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"3846d27dab8b40f2a7b505ea604b1d43",
                  "label":"",
                  "parentDynamicPanel":"b927cc8c05bc4c7d8a97ec3aa6a9904c",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":40,
                      "height":40},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3713bdf2db584e8c943a4c8fb26724da",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b927cc8c05bc4c7d8a97ec3aa6a9904c",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":40,
                          "height":40},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/actions_configuration/u47.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"e21554c674c8404db3ddb644b17a80f3",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":193,
              "y":51},
            "size":{
              "width":591,
              "height":118}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87e0d4c46aa04c65a4a6818817b01813",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"bold",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "size":{
                  "width":58,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b1e0af62332d44a289c61505c2416458",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontWeight":"bold",
                    "horizontalAlignment":"center",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF666666},
                    "size":{
                      "width":58,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/points_customization/u14.png"}},
{
              "id":"2760c8d3fed74a258d4f742fe3be16a9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "location":{
                  "x":0,
                  "y":20},
                "size":{
                  "width":58,
                  "height":34}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4ce650dbd0044cf5a3e4670553d7de14",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "horizontalAlignment":"center",
                    "location":{
                      "x":0,
                      "y":20},
                    "size":{
                      "width":58,
                      "height":34}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/points_customization/u24.png"}},
{
              "id":"ec5dc3f383054c9893523fd32c7d4f75",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"bold",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":170,
                  "y":0},
                "size":{
                  "width":172,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f2bb66e0101e44008c440114be94a4ae",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontWeight":"bold",
                    "horizontalAlignment":"center",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF666666},
                    "location":{
                      "x":170,
                      "y":0},
                    "size":{
                      "width":172,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/points_customization/u18.png"}},
{
              "id":"3a869aa898cf4a7884035a127e68c7fe",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":170,
                  "y":20},
                "size":{
                  "width":172,
                  "height":34}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"618cf4ad24ef47c8b99612efb775f6e7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":170,
                      "y":20},
                    "size":{
                      "width":172,
                      "height":34}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/points_customization/u28.png"}},
{
              "id":"5e303785e72e4d85a05b4428f12d96b6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"bold",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":342,
                  "y":0},
                "size":{
                  "width":107,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"93651a0b8d4b41c7a7a0a8979a44c530",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontWeight":"bold",
                    "horizontalAlignment":"center",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF666666},
                    "location":{
                      "x":342,
                      "y":0},
                    "size":{
                      "width":107,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/points_customization/u20.png"}},
{
              "id":"b98b25df2c204db29e4b08571cf5bdf8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":342,
                  "y":20},
                "size":{
                  "width":107,
                  "height":34}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"93bc1a8eb21a48e89ee1b3c73e9e413f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":342,
                      "y":20},
                    "size":{
                      "width":107,
                      "height":34}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/points_customization/u30.png"}},
{
              "id":"54345bf03dcb43a1a6d297f03adc7b2b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "location":{
                  "x":0,
                  "y":54},
                "size":{
                  "width":58,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cd4ec3c6ff5d4cdd8251c7c774091e9c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "horizontalAlignment":"center",
                    "location":{
                      "x":0,
                      "y":54},
                    "size":{
                      "width":58,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/points_customization/u34.png"}},
{
              "id":"70081c4f205243ec8bf1fcf820fb934e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":170,
                  "y":54},
                "size":{
                  "width":172,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4e788bdbebf24dc3b6d62707f46efc7b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":170,
                      "y":54},
                    "size":{
                      "width":172,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/points_customization/u38.png"}},
{
              "id":"d121d38d951b4eb1a749411df8c96307",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":342,
                  "y":54},
                "size":{
                  "width":107,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d38a9cb7a9394864b1c9be97f64b28c1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":342,
                      "y":54},
                    "size":{
                      "width":107,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/points_customization/u40.png"}},
{
              "id":"0633357426a54308a3d1ea6d6390c852",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "location":{
                  "x":0,
                  "y":84},
                "size":{
                  "width":58,
                  "height":34}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"aec21a2bfa6a4889862776ffca33bcf4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "horizontalAlignment":"center",
                    "location":{
                      "x":0,
                      "y":84},
                    "size":{
                      "width":58,
                      "height":34}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/points_customization/u44.png"}},
{
              "id":"17a558c884514a96ab59d8a19907b8c5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":170,
                  "y":84},
                "size":{
                  "width":172,
                  "height":34}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ce4dfd7ab34447f8ba3f964da806153c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":170,
                      "y":84},
                    "size":{
                      "width":172,
                      "height":34}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/points_customization/u48.png"}},
{
              "id":"5479495175134f4bbc9f37f85fe80e19",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":342,
                  "y":84},
                "size":{
                  "width":107,
                  "height":34}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"587c629fcb9244d6acb5949a53bcec36",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":342,
                      "y":84},
                    "size":{
                      "width":107,
                      "height":34}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/points_customization/u50.png"}},
{
              "id":"4057a7fb0ee344b1921f0378a8ff3954",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"bold",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":449,
                  "y":0},
                "size":{
                  "width":141,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"071c2d0ed27443b88ce7b5ef2b64980d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontWeight":"bold",
                    "horizontalAlignment":"center",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF666666},
                    "location":{
                      "x":449,
                      "y":0},
                    "size":{
                      "width":141,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/points_customization/u22.png"}},
{
              "id":"f3caf5b52912445ca0ceef188d5d600e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":449,
                  "y":20},
                "size":{
                  "width":141,
                  "height":34}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2af21cf652394e55a4262ba4950eb9d9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":449,
                      "y":20},
                    "size":{
                      "width":141,
                      "height":34}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/points_customization/u32.png"}},
{
              "id":"5bd779c48083403b90b75a1f1a028dee",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":449,
                  "y":54},
                "size":{
                  "width":141,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"40e12ec706d8410ab858820387c63af4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":449,
                      "y":54},
                    "size":{
                      "width":141,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/points_customization/u42.png"}},
{
              "id":"2191395434ad4b65893f8a34c9ce759d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":449,
                  "y":84},
                "size":{
                  "width":141,
                  "height":34}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e6406a277aba49fa9326e4160bb1c830",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":449,
                      "y":84},
                    "size":{
                      "width":141,
                      "height":34}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/points_customization/u52.png"}},
{
              "id":"a184da03fa7c48ee89a0f2a063795fe4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"bold",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":58,
                  "y":0},
                "size":{
                  "width":112,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c99e4c2d132f4a258f4c785c5584dda5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontWeight":"bold",
                    "horizontalAlignment":"center",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF666666},
                    "location":{
                      "x":58,
                      "y":0},
                    "size":{
                      "width":112,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/points_customization/u16.png"}},
{
              "id":"5ecefa867fa64716b9543a4855dc39b7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":58,
                  "y":20},
                "size":{
                  "width":112,
                  "height":34}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e15aba4d26de4d73aaa09704e707836f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":58,
                      "y":20},
                    "size":{
                      "width":112,
                      "height":34}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/points_customization/u26.png"}},
{
              "id":"da9d265021ef4954a918872ce81d692f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":58,
                  "y":54},
                "size":{
                  "width":112,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"30b72fedcdb04fbdb082b6891b402148",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":58,
                      "y":54},
                    "size":{
                      "width":112,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/points_customization/u36.png"}},
{
              "id":"e1bdd6fa2b534251b746695486988dd7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":58,
                  "y":84},
                "size":{
                  "width":112,
                  "height":34}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9db48f3e4f4f43049ff55ba378bdb9c1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":58,
                      "y":84},
                    "size":{
                      "width":112,
                      "height":34}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/points_customization/u46.png"}}]},
{
          "id":"25dcd6ed43d049be8629a5d0f488fae9",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":646,
              "y":75},
            "size":{
              "width":132,
              "height":26}},
          "adaptiveStyles":{
},
          "masterId":"b8502e6abb054c539ccc342424993a77"},
{
          "id":"36da1a147a2f4cd2a3428bfa54108d73",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":646,
              "y":107},
            "size":{
              "width":132,
              "height":26}},
          "adaptiveStyles":{
},
          "masterId":"b8502e6abb054c539ccc342424993a77"},
{
          "id":"bbae6b08ad6647268d167ef8bae41c54",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":646,
              "y":139},
            "size":{
              "width":132,
              "height":26}},
          "adaptiveStyles":{
},
          "masterId":"b8502e6abb054c539ccc342424993a77"},
{
          "id":"b4e2c1866747485ba20cad775989d7a1",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":75},
            "size":{
              "width":157,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"399051f508e9468f9960013a3f9d6d78",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":111},
            "size":{
              "width":157,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"c47264382c2949f9a3a7177cf1ba7416",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":258,
              "y":79},
            "size":{
              "width":100,
              "height":19}},
          "adaptiveStyles":{
},
          "masterId":"8434d4db452f4a5d8431e298788320f3"},
{
          "id":"d47e9ecddf7f46608b6185c5225a1593",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":258,
              "y":111},
            "size":{
              "width":100,
              "height":19}},
          "adaptiveStyles":{
},
          "masterId":"8434d4db452f4a5d8431e298788320f3"},
{
          "id":"e596e3a57b314357b35452b3289007fa",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":258,
              "y":143},
            "size":{
              "width":100,
              "height":19}},
          "adaptiveStyles":{
},
          "masterId":"8434d4db452f4a5d8431e298788320f3"},
{
          "id":"ada9a42010da42f9a93364060a0e4bad",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":535,
              "y":73},
            "size":{
              "width":106,
              "height":33}},
          "adaptiveStyles":{
}},
{
          "id":"7ff5eff8398841cfb9c63699a9328947",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":535,
              "y":105},
            "size":{
              "width":106,
              "height":31}},
          "adaptiveStyles":{
}},
{
          "id":"2f7f3ea612664537b7aa2c048b852d31",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":641,
              "y":137},
            "size":{
              "width":144,
              "height":47}},
          "adaptiveStyles":{
},
          "masterId":"a9595e541ee64f5593d6577b23b0c080"},
{
          "id":"defe0e6915b54791a820a337349108b1",
          "label":"New rule row hider",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":193,
              "y":136},
            "size":{
              "width":591,
              "height":51}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"d190cbf9209243b8a836c1aac352abf0",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"8c590a64ec1147189928e1788382de38",
                  "label":"",
                  "parentDynamicPanel":"defe0e6915b54791a820a337349108b1",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":596,
                      "height":54},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"38eb1693153f4b5a8645010a7d054c40",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"defe0e6915b54791a820a337349108b1",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":596,
                          "height":54},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/points_customization/u101.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"9e6eab25c5b448258ad3d359a584e13c",
              "label":"State2",
              "type":"Axure:PanelDiagram",
              "objects":[],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"07a2049a101f4986b649083de8aaf3f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":643,
              "y":138},
            "size":{
              "width":139,
              "height":44},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b051f30e32b4626a76c19d09770f954",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":643,
                  "y":138},
                "size":{
                  "width":139,
                  "height":44},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set New rule row hider to State2 slide down in 1000ms show if hidden",
                      "panelsToStates":[{
                          "panelPath":["defe0e6915b54791a820a337349108b1"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":true,
                            "options":{
                              "animateIn":{
                                "easing":"slideDown",
                                "duration":1000},
                              "compress":false}}}]},
{
                      "action":"moveWidget",
                      "description":"Move New rule row hider by (0,200)",
                      "objectsToMoves":[{
                          "objectPath":["defe0e6915b54791a820a337349108b1"],
                          "moveInfo":{
                            "moveType":"delta",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"200",
                              "stos":[]},
                            "options":{
}}}]},
{
                      "action":"moveWidget",
                      "description":"Move Widget",
                      "objectsToMoves":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "b8502e6abb054c539ccc342424993a77":{
      "packageId":"b8502e6abb054c539ccc342424993a77",
      "type":"Axure:Master",
      "name":"Delete button with minus",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"c380393f54d54942bbe8f9f51b57a7cc",
            "label":"",
            "type":"referenceDiagramObject",
            "styleType":"referenceDiagramObject",
            "visible":true,
            "style":{
              "location":{
                "x":-0.199996948242188,
                "y":0},
              "size":{
                "width":132,
                "height":26}},
            "adaptiveStyles":{
},
            "masterId":"5a1a58e786304e89a234b813399663d0"},
{
            "id":"17fba24ee08641ada992d3ea0cbdc623",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "location":{
                "x":101,
                "y":3},
              "size":{
                "width":20,
                "height":20},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"738dd02334b84bc790396682546dc570",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "location":{
                    "x":101,
                    "y":3},
                  "size":{
                    "width":20,
                    "height":20},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/actions_configuration/u95.png",
              "normal~":"images/actions_configuration/u95.png",
              "normal~":"images/actions_configuration/u95.png"}}]}},
    "5a1a58e786304e89a234b813399663d0":{
      "packageId":"5a1a58e786304e89a234b813399663d0",
      "type":"Axure:Master",
      "name":"Delete button without minus",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"ebd7e2fe9e4749c68e470751cfe24721",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Arial Bold', 'Arial'",
              "fontSize":"18px",
              "fontWeight":"bold",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "size":{
                "width":132,
                "height":26},
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bdbaaf0c47fe4782b647ab2237c783ec",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Bold', 'Arial'",
                  "fontSize":"18px",
                  "fontWeight":"bold",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "size":{
                    "width":132,
                    "height":26},
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/actions_configuration/u93.png",
              "normal~":"images/actions_configuration/u93.png",
              "normal~":"images/actions_configuration/u93.png"}}]}},
    "8434d4db452f4a5d8431e298788320f3":{
      "packageId":"8434d4db452f4a5d8431e298788320f3",
      "type":"Axure:Master",
      "name":"Switcher",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"b1c94b16163f4a3e962392b6a4476090",
            "label":"Switcher",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "size":{
                "width":100,
                "height":19}},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"c5c2c66862d24e5cab61cdd504b6f9b3",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"2b6643dd93b242d3ad0893fc8a3ca583",
                    "label":"",
                    "parentDynamicPanel":"b1c94b16163f4a3e962392b6a4476090",
                    "panelIndex":0,
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":5,
                        "y":3},
                      "size":{
                        "width":85,
                        "height":15},
                      "borderWidth":"-1"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"ed5b3e2364584002aa9d1761fab73a34",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"b1c94b16163f4a3e962392b6a4476090",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":5,
                            "y":3},
                          "size":{
                            "width":85,
                            "height":15},
                          "borderWidth":"-1"},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"setPanelState",
                                "description":"Set Switcher to State2 show if hidden",
                                "panelsToStates":[{
                                    "panelPath":["b1c94b16163f4a3e962392b6a4476090"],
                                    "stateInfo":{
                                      "setStateType":"diagram",
                                      "stateNumber":2,
                                      "stateValue":{
                                        "exprType":"stringLiteral",
                                        "value":"1",
                                        "stos":[]},
                                      "loop":false,
                                      "showWhenSet":true,
                                      "options":{
                                        "compress":false}}}]}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/plugin_configuration/u53.png",
                      "normal~":"images/plugin_configuration/u53.png",
                      "normal~":"images/plugin_configuration/u53.png"}}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}},
{
                "id":"cd3f1dbd59434a3581f7087b8b4cddb2",
                "label":"State2",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"96184e07cef040969d5acef58f4e2e9d",
                    "label":"",
                    "parentDynamicPanel":"b1c94b16163f4a3e962392b6a4476090",
                    "panelIndex":1,
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":5,
                        "y":3},
                      "size":{
                        "width":85,
                        "height":15},
                      "borderWidth":"-1"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"b315c731df1541eeb8d73c30e9a59c95",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"b1c94b16163f4a3e962392b6a4476090",
                        "panelIndex":1,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":5,
                            "y":3},
                          "size":{
                            "width":85,
                            "height":15},
                          "borderWidth":"-1"},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"setPanelState",
                                "description":"Set Switcher to State1 show if hidden",
                                "panelsToStates":[{
                                    "panelPath":["b1c94b16163f4a3e962392b6a4476090"],
                                    "stateInfo":{
                                      "setStateType":"diagram",
                                      "stateNumber":1,
                                      "stateValue":{
                                        "exprType":"stringLiteral",
                                        "value":"1",
                                        "stos":[]},
                                      "loop":false,
                                      "showWhenSet":true,
                                      "options":{
                                        "compress":false}}}]}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/plugin_configuration/u55.png",
                      "normal~":"images/plugin_configuration/u55.png",
                      "normal~":"images/plugin_configuration/u55.png"}}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}}]}]}},
    "a9595e541ee64f5593d6577b23b0c080":{
      "packageId":"a9595e541ee64f5593d6577b23b0c080",
      "type":"Axure:Master",
      "name":"Add new button with plus",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"14a2ffa87c614668ab9840d825c3d277",
            "label":"Add new button with plus dynamic panel",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "size":{
                "width":144,
                "height":47}},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"0f907c7295064ada93fd2d15a91df452",
                "label":"State2",
                "type":"Axure:PanelDiagram",
                "objects":[],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}},
{
                "id":"5e21a017b48f402786527ae340f5a92a",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"076fdc0f69ae4c16a891514384509085",
                    "label":"",
                    "parentDynamicPanel":"14a2ffa87c614668ab9840d825c3d277",
                    "panelIndex":1,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fontName":"'Arial Bold', 'Arial'",
                      "fontSize":"20px",
                      "fontWeight":"bold",
                      "horizontalAlignment":"left",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "size":{
                        "width":142,
                        "height":45},
                      "cornerRadiusTopLeft":"5"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"3205471e0996416e9cfb326d45481cdb",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"14a2ffa87c614668ab9840d825c3d277",
                        "panelIndex":1,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Arial Bold', 'Arial'",
                          "fontSize":"20px",
                          "fontWeight":"bold",
                          "horizontalAlignment":"left",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "size":{
                            "width":142,
                            "height":45},
                          "cornerRadiusTopLeft":"5"},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/actions_configuration/u54.png"}},
{
                    "id":"a1793f0b35194de2a8c8682275abc1d1",
                    "label":"",
                    "parentDynamicPanel":"14a2ffa87c614668ab9840d825c3d277",
                    "panelIndex":1,
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":101,
                        "y":6},
                      "size":{
                        "width":34,
                        "height":32},
                      "borderWidth":"-1"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"e2496c49e22d41aab23fd61215650d1b",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"14a2ffa87c614668ab9840d825c3d277",
                        "panelIndex":1,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":101,
                            "y":6},
                          "size":{
                            "width":34,
                            "height":32},
                          "borderWidth":"-1"},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/actions_configuration/u56.png"}}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}}]}]}}},
  "objectPaths":{
    "41810afb3ba94e909d3ffca3f01892cb":{
      "scriptId":"u0"},
    "3024f4d8af974ff1a8b43881c90f9d42":{
      "scriptId":"u1"},
    "72a448fc11b642bbaf45b433f54848e0":{
      "scriptId":"u2"},
    "9f82b39877a541b68947ed42b6d14bba":{
      "scriptId":"u3"},
    "43f72c25a65540508b403d9c725dfe5f":{
      "scriptId":"u4"},
    "d7879956e5e44af7bd99cf644e3ba540":{
      "scriptId":"u5"},
    "a197f19f0fc844c5b73f976397c41a26":{
      "scriptId":"u6"},
    "26b5fe5a087b44b1b7d253e5862c7c7f":{
      "scriptId":"u7"},
    "2c92bc85cc674b61bbd4f32d64354bf8":{
      "scriptId":"u8"},
    "5f6f3ac9b15e4b15b94b3a20eee7c6cf":{
      "scriptId":"u9"},
    "b927cc8c05bc4c7d8a97ec3aa6a9904c":{
      "scriptId":"u10"},
    "3846d27dab8b40f2a7b505ea604b1d43":{
      "scriptId":"u11"},
    "3713bdf2db584e8c943a4c8fb26724da":{
      "scriptId":"u12"},
    "e21554c674c8404db3ddb644b17a80f3":{
      "scriptId":"u13"},
    "87e0d4c46aa04c65a4a6818817b01813":{
      "scriptId":"u14"},
    "b1e0af62332d44a289c61505c2416458":{
      "scriptId":"u15"},
    "a184da03fa7c48ee89a0f2a063795fe4":{
      "scriptId":"u16"},
    "c99e4c2d132f4a258f4c785c5584dda5":{
      "scriptId":"u17"},
    "ec5dc3f383054c9893523fd32c7d4f75":{
      "scriptId":"u18"},
    "f2bb66e0101e44008c440114be94a4ae":{
      "scriptId":"u19"},
    "5e303785e72e4d85a05b4428f12d96b6":{
      "scriptId":"u20"},
    "93651a0b8d4b41c7a7a0a8979a44c530":{
      "scriptId":"u21"},
    "4057a7fb0ee344b1921f0378a8ff3954":{
      "scriptId":"u22"},
    "071c2d0ed27443b88ce7b5ef2b64980d":{
      "scriptId":"u23"},
    "2760c8d3fed74a258d4f742fe3be16a9":{
      "scriptId":"u24"},
    "4ce650dbd0044cf5a3e4670553d7de14":{
      "scriptId":"u25"},
    "5ecefa867fa64716b9543a4855dc39b7":{
      "scriptId":"u26"},
    "e15aba4d26de4d73aaa09704e707836f":{
      "scriptId":"u27"},
    "3a869aa898cf4a7884035a127e68c7fe":{
      "scriptId":"u28"},
    "618cf4ad24ef47c8b99612efb775f6e7":{
      "scriptId":"u29"},
    "b98b25df2c204db29e4b08571cf5bdf8":{
      "scriptId":"u30"},
    "93bc1a8eb21a48e89ee1b3c73e9e413f":{
      "scriptId":"u31"},
    "f3caf5b52912445ca0ceef188d5d600e":{
      "scriptId":"u32"},
    "2af21cf652394e55a4262ba4950eb9d9":{
      "scriptId":"u33"},
    "54345bf03dcb43a1a6d297f03adc7b2b":{
      "scriptId":"u34"},
    "cd4ec3c6ff5d4cdd8251c7c774091e9c":{
      "scriptId":"u35"},
    "da9d265021ef4954a918872ce81d692f":{
      "scriptId":"u36"},
    "30b72fedcdb04fbdb082b6891b402148":{
      "scriptId":"u37"},
    "70081c4f205243ec8bf1fcf820fb934e":{
      "scriptId":"u38"},
    "4e788bdbebf24dc3b6d62707f46efc7b":{
      "scriptId":"u39"},
    "d121d38d951b4eb1a749411df8c96307":{
      "scriptId":"u40"},
    "d38a9cb7a9394864b1c9be97f64b28c1":{
      "scriptId":"u41"},
    "5bd779c48083403b90b75a1f1a028dee":{
      "scriptId":"u42"},
    "40e12ec706d8410ab858820387c63af4":{
      "scriptId":"u43"},
    "0633357426a54308a3d1ea6d6390c852":{
      "scriptId":"u44"},
    "aec21a2bfa6a4889862776ffca33bcf4":{
      "scriptId":"u45"},
    "e1bdd6fa2b534251b746695486988dd7":{
      "scriptId":"u46"},
    "9db48f3e4f4f43049ff55ba378bdb9c1":{
      "scriptId":"u47"},
    "17a558c884514a96ab59d8a19907b8c5":{
      "scriptId":"u48"},
    "ce4dfd7ab34447f8ba3f964da806153c":{
      "scriptId":"u49"},
    "5479495175134f4bbc9f37f85fe80e19":{
      "scriptId":"u50"},
    "587c629fcb9244d6acb5949a53bcec36":{
      "scriptId":"u51"},
    "2191395434ad4b65893f8a34c9ce759d":{
      "scriptId":"u52"},
    "e6406a277aba49fa9326e4160bb1c830":{
      "scriptId":"u53"},
    "25dcd6ed43d049be8629a5d0f488fae9":{
      "scriptId":"u54",
      "c380393f54d54942bbe8f9f51b57a7cc":{
        "scriptId":"u55",
        "ebd7e2fe9e4749c68e470751cfe24721":{
          "scriptId":"u56"},
        "bdbaaf0c47fe4782b647ab2237c783ec":{
          "scriptId":"u57"}},
      "17fba24ee08641ada992d3ea0cbdc623":{
        "scriptId":"u58"},
      "738dd02334b84bc790396682546dc570":{
        "scriptId":"u59"}},
    "36da1a147a2f4cd2a3428bfa54108d73":{
      "scriptId":"u60",
      "c380393f54d54942bbe8f9f51b57a7cc":{
        "scriptId":"u61",
        "ebd7e2fe9e4749c68e470751cfe24721":{
          "scriptId":"u62"},
        "bdbaaf0c47fe4782b647ab2237c783ec":{
          "scriptId":"u63"}},
      "17fba24ee08641ada992d3ea0cbdc623":{
        "scriptId":"u64"},
      "738dd02334b84bc790396682546dc570":{
        "scriptId":"u65"}},
    "bbae6b08ad6647268d167ef8bae41c54":{
      "scriptId":"u66",
      "c380393f54d54942bbe8f9f51b57a7cc":{
        "scriptId":"u67",
        "ebd7e2fe9e4749c68e470751cfe24721":{
          "scriptId":"u68"},
        "bdbaaf0c47fe4782b647ab2237c783ec":{
          "scriptId":"u69"}},
      "17fba24ee08641ada992d3ea0cbdc623":{
        "scriptId":"u70"},
      "738dd02334b84bc790396682546dc570":{
        "scriptId":"u71"}},
    "b4e2c1866747485ba20cad775989d7a1":{
      "scriptId":"u72"},
    "399051f508e9468f9960013a3f9d6d78":{
      "scriptId":"u73"},
    "c47264382c2949f9a3a7177cf1ba7416":{
      "scriptId":"u74",
      "b1c94b16163f4a3e962392b6a4476090":{
        "scriptId":"u75"},
      "2b6643dd93b242d3ad0893fc8a3ca583":{
        "scriptId":"u76"},
      "ed5b3e2364584002aa9d1761fab73a34":{
        "scriptId":"u77"},
      "96184e07cef040969d5acef58f4e2e9d":{
        "scriptId":"u78"},
      "b315c731df1541eeb8d73c30e9a59c95":{
        "scriptId":"u79"}},
    "d47e9ecddf7f46608b6185c5225a1593":{
      "scriptId":"u80",
      "b1c94b16163f4a3e962392b6a4476090":{
        "scriptId":"u81"},
      "2b6643dd93b242d3ad0893fc8a3ca583":{
        "scriptId":"u82"},
      "ed5b3e2364584002aa9d1761fab73a34":{
        "scriptId":"u83"},
      "96184e07cef040969d5acef58f4e2e9d":{
        "scriptId":"u84"},
      "b315c731df1541eeb8d73c30e9a59c95":{
        "scriptId":"u85"}},
    "e596e3a57b314357b35452b3289007fa":{
      "scriptId":"u86",
      "b1c94b16163f4a3e962392b6a4476090":{
        "scriptId":"u87"},
      "2b6643dd93b242d3ad0893fc8a3ca583":{
        "scriptId":"u88"},
      "ed5b3e2364584002aa9d1761fab73a34":{
        "scriptId":"u89"},
      "96184e07cef040969d5acef58f4e2e9d":{
        "scriptId":"u90"},
      "b315c731df1541eeb8d73c30e9a59c95":{
        "scriptId":"u91"}},
    "ada9a42010da42f9a93364060a0e4bad":{
      "scriptId":"u92"},
    "7ff5eff8398841cfb9c63699a9328947":{
      "scriptId":"u93"},
    "2f7f3ea612664537b7aa2c048b852d31":{
      "scriptId":"u94",
      "14a2ffa87c614668ab9840d825c3d277":{
        "scriptId":"u95"},
      "076fdc0f69ae4c16a891514384509085":{
        "scriptId":"u96"},
      "3205471e0996416e9cfb326d45481cdb":{
        "scriptId":"u97"},
      "a1793f0b35194de2a8c8682275abc1d1":{
        "scriptId":"u98"},
      "e2496c49e22d41aab23fd61215650d1b":{
        "scriptId":"u99"}},
    "defe0e6915b54791a820a337349108b1":{
      "scriptId":"u100"},
    "8c590a64ec1147189928e1788382de38":{
      "scriptId":"u101"},
    "38eb1693153f4b5a8645010a7d054c40":{
      "scriptId":"u102"},
    "07a2049a101f4986b649083de8aaf3f6":{
      "scriptId":"u103"},
    "5b051f30e32b4626a76c19d09770f954":{
      "scriptId":"u104"}}});