package eu.trentorise.game.model

import eu.trentorise.game.notification.BadgeNotification;

global java.util.ArrayList pr_parks;
global eu.trentorise.game.managers.NotificationManager notificationSrv;

/* ***************************************************************************
  POINTS
  
*************************************************************************** */

rule "20 point badge"
	salience -1000
when
    PointConcept(score >= 20.0)
    $bc : BadgeCollectionConcept(badgeEarned not contains '20-point')
    Game( $gameId: id)
    Player( $playerId : id)
then
	log("apply \'20-point badge\'");
	$bc.getBadgeEarned().add('20-point');
	BadgeNotification notification = new BadgeNotification($gameId,$playerId,'20-point');
	notificationSrv.notificate(notification);
	log("notificate \'20-point badge\'");
end

rule "50 point badge"
	salience -1000
when
    PointConcept(score >= 50.0)
    $bc : BadgeCollectionConcept(badgeEarned not contains '50-point')
    Game( $gameId: id)
    Player( $playerId : id)
then
	log("apply \'50-point badge\'");
	$bc.getBadgeEarned().add('50-point');
	BadgeNotification notification = new BadgeNotification($gameId,$playerId,'50-point');
	notificationSrv.notificate(notification);
	log("notificate \'50-point badge\'");
end

rule "100 point badge"
	salience -1000
when
    PointConcept(score >= 100.0)
    $bc : BadgeCollectionConcept(badgeEarned not contains '100-point')
then
	log("apply \'100-point badge\'");
	$bc.getBadgeEarned().add('100-point');
end

rule "200 point badge"
	salience -1000
when
    PointConcept(score >= 200.0)
    $bc : BadgeCollectionConcept(badgeEarned not contains '200-point')
then
	log("apply \'200-point badge\'");
	$bc.getBadgeEarned().add('200-point');
end

rule "500 point badge"
	salience -1000
when
    PointConcept(score >= 500.0)
    $bc : BadgeCollectionConcept(badgeEarned not contains '500-point')
then
	log("apply \'500-point badge\'");
	$bc.getBadgeEarned().add('500-point');
end

rule "1000 point badge"
	salience -1000
when
    PointConcept(score >= 1000.0)
    $bc : BadgeCollectionConcept(badgeEarned not contains '1000-point')
then
	log("apply \'1000-point badge\'");
	$bc.getBadgeEarned().add('1000-point');
end

rule "2000 point badge"
	salience -1000
when
    PointConcept(score >= 2000.0)
    $bc : BadgeCollectionConcept(badgeEarned not contains '2000-point')
then
	log("apply \'2000-point badge\'");
	$bc.getBadgeEarned().add('2000-point');
end

/* ***************************************************************************
E-MOTION  
  
*************************************************************************** */

rule "e-motion badge"
	salience -1000
when
    InputData(data['bikesharing'] == true)
    $bc : BadgeCollectionConcept(badgeEarned not contains 'e-motion')
    Game( $gameId: id)
    Player( $playerId : id)
then
	log("apply \'e-motion badge\'");
	$bc.getBadgeEarned().add('e-motion');
	BadgeNotification notification = new BadgeNotification($gameId,$playerId,'e-motion');
	notificationSrv.notificate(notification);
	log("notificate \'e-motion badge\'");
end

/* ***************************************************************************
PARK  
  
*************************************************************************** */
rule "park badge"
	salience -1000
when
    InputData( $park : data['park'] != null)
    $bc : BadgeCollectionConcept(badgeEarned not contains $park)
then
	log("apply \'park badge\' " + $park);
	$bc.getBadgeEarned().add((String) $park);
end


/* ***************************************************************************
P+R
  
*************************************************************************** */
rule "p+r badge"
	salience -1000
when
    InputData(data['park'] memberOf pr_parks)
    InputData(data['walkDistance'] != null || data['bikeDistance'] != null || data['busDistance'] != null || data['trainDistance'] != null)
    $bc : BadgeCollectionConcept(badgeEarned not contains 'p+r')
then
	log("apply \'p+r badge\'");
	$bc.getBadgeEarned().add('p+r');
	update( $bc );
end


/* ***************************************************************************
CLASSIFICATION
  
*************************************************************************** */
rule "classification gold badge"
	salience -1000
when
    Action( id == 'classification')
    InputData( data['classification_name'] == 'final classification')
    InputData( data['classification_position'] == 1)
    $bc : BadgeCollectionConcept(badgeEarned not contains 'gold medal')
then
	log("apply \'gold medal badge\'");
	$bc.getBadgeEarned().add('gold medal');
	update( $bc );
end

rule "classification silver badge"
	salience -1000
when
    Action( id == 'classification')
    InputData( data['classification_name'] == 'final classification')
    InputData( data['classification_position'] == 2)
    $bc : BadgeCollectionConcept(badgeEarned not contains 'silver medal')
then
	log("apply \'silver medal badge\'");
	$bc.getBadgeEarned().add('silver medal');
	update( $bc );
end

rule "classification bronze badge"
	salience -1000
when
    Action( id == 'classification')
    InputData( data['classification_name'] == 'final classification')
    InputData( data['classification_position'] == 3)
    $bc : BadgeCollectionConcept(badgeEarned not contains 'bronze medal')
then
	log("apply \'bronze medal badge\'");
	$bc.getBadgeEarned().add('bronze medal');
	update( $bc );
end


