package eu.trentorise.game.model

rule "update green points"
when
    InputData( $bike : data["bikeDistance"], $walk : data["walkDistance"], $bus : data["busDistance"], $train : data["trainDistance"])
    $pc : PointConcept(name == "green leaves")
then
	log("apply \'update green points\'");
	Double bike = $bike != null ? (Double) $bike : 0;
	Double walk = $walk != null ? (Double) $walk : 0;
    Double bus = $bus != null ? (Double) $bus : 0;
	Double train = $train != null ? (Double) $train : 0;

	Integer dist1 = (int) (bike + walk);
	//log("dist1" + dist1);
	Integer dist2 = (int) (bus + train);
    //log("dist2" + dist2);
    
    $pc.setScore($pc.getScore() + 2.0 * dist1 + 1.0 * dist2);
    update($pc);
end

rule "p+r points"
when
    InputData(data['park'] in ('QUERCIA','STADIO'))
    InputData(data['walkDistance'] != null || data['bikeDistance'] != null || data['busDistance'] != null || data['trainDistance'] != null) 
    $pc : PointConcept(name == "green leaves")
then
	log("apply \'p+r green points\'");
	$pc.setScore($pc.getScore() + 5.0);
    update($pc);
end

