package eu.trentorise.game.model


global java.lang.Integer walk_bike_points;
global java.lang.Integer bus_train_points;
global java.lang.Integer pr_points;
global java.util.ArrayList pr_parks;

rule "update green points"
when
    InputData( $bike : data["bikeDistance"], $walk : data["walkDistance"], $bus : data["busDistance"], $train : data["trainDistance"])
    $pc : PointConcept(name == "green leaves")
then
	log("apply \'update green points\'");
	Double bike = $bike != null ? (Double) $bike : 0;
	Double walk = $walk != null ? (Double) $walk : 0;
    Double bus = $bus != null ? (Double) $bus : 0;
	Double train = $train != null ? (Double) $train : 0;

	Integer dist1 = (int) (bike + walk);
	//log("dist1" + dist1);
	Integer dist2 = (int) (bus + train);
    //log("dist2" + dist2);
    
    $pc.setScore($pc.getScore() + walk_bike_points * dist1 + bus_train_points * dist2);
    update($pc);
end

rule "p+r points"
when
    InputData(data['park'] memberOf pr_parks)
    InputData(data['walkDistance'] != null || data['bikeDistance'] != null || data['busDistance'] != null || data['trainDistance'] != null) 
    $pc : PointConcept(name == "green leaves")
then
	log("apply \'p+r green points\'");
	$pc.setScore($pc.getScore() + pr_points);
    update($pc);
end

