package eu.trentorise.game.model

import eu.trentorise.game.notification.BadgeNotification;

global eu.trentorise.game.managers.NotificationManager notificationSrv;


rule "10 point health badge"
	salience -1000
when
    PointConcept(name == 'health', score >= 10.0)
    $bc : BadgeCollectionConcept(badgeEarned not contains '10-point-health')
    Game( $gameId: id)
    Player( $playerId : id)
then
	log("apply \'10-point-health badge\'");
	$bc.getBadgeEarned().add('10-point-health');
	BadgeNotification notification = new BadgeNotification($gameId,$playerId,'10-point-health');
	notificationSrv.notificate(notification);
	log("notificate \'10-point-health badge\'");
end

rule "25 point health badge"
	salience -1000
when
    PointConcept(name == 'health', score >= 25.0)
    $bc : BadgeCollectionConcept(badgeEarned not contains '25-point-health')
    Game( $gameId: id)
    Player( $playerId : id)
then
	log("apply \'25-point-health badge\'");
	$bc.getBadgeEarned().add('25-point-health');
	BadgeNotification notification = new BadgeNotification($gameId,$playerId,'25-point-health');
	notificationSrv.notificate(notification);
	log("notificate \'25-point-health badge\'");
end


rule "50 point health badge"
	salience -1000
when
    PointConcept(name == 'health', score >= 50.0)
    $bc : BadgeCollectionConcept(badgeEarned not contains '50-point-health')
    Game( $gameId: id)
    Player( $playerId : id)
then
	log("apply \'50-point-health badge\'");
	$bc.getBadgeEarned().add('50-point-health');
	BadgeNotification notification = new BadgeNotification($gameId,$playerId,'50-point-health');
	notificationSrv.notificate(notification);
	log("notificate \'50-point-health badge\'");
end

rule "100 point health badge"
	salience -1000
when
    PointConcept(name == 'health', score >= 100.0)
    $bc : BadgeCollectionConcept(badgeEarned not contains '100-point-health')
    Game( $gameId: id)
    Player( $playerId : id)
then
	log("apply \'100-point-health badge\'");
	$bc.getBadgeEarned().add('100-point-health');
	BadgeNotification notification = new BadgeNotification($gameId,$playerId,'100-point-health');
	notificationSrv.notificate(notification);
	log("notificate \'100-point-health badge\'");
end

rule "200 point health badge"
	salience -1000
when
    PointConcept(name == 'health', score >= 200.0)
    $bc : BadgeCollectionConcept(badgeEarned not contains '200-point-health')
    Game( $gameId: id)
    Player( $playerId : id)
then
	log("apply \'200-point-health badge\'");
	$bc.getBadgeEarned().add('200-point-health');
	BadgeNotification notification = new BadgeNotification($gameId,$playerId,'200-point-health');
	notificationSrv.notificate(notification);
	log("notificate \'200-point-health badge\'");
end