package eu.trentorise.game.model


rule "init point"
	salience 1000
when
    not PointConcept(name == "green leaves")
then
	log("apply \'init green leaves\'");
	PointConcept pc = new PointConcept('green leaves');
	insert(pc);
end


rule "init badge collection"
	salience 1000
when
    not BadgeCollectionConcept()
then
	log("apply \'init badge collection\'");
	BadgeCollectionConcept bcc = new BadgeCollectionConcept();
	insert(bcc);
end