package eu.trentorise.game.model

import eu.trentorise.game.notification.BadgeNotification;

global eu.trentorise.game.managers.NotificationManager notificationSrv;


rule "10 point pr badge"
	salience -1000
when
    PointConcept(name == 'p+r', score >= 10.0)
    $bc : BadgeCollectionConcept(badgeEarned not contains '10-point-pr')
    Game( $gameId: id)
    Player( $playerId : id)
then
	log("apply \'10-point-pr badge\'");
	$bc.getBadgeEarned().add('10-point-pr');
	BadgeNotification notification = new BadgeNotification($gameId,$playerId,'10-point-pr');
	notificationSrv.notificate(notification);
	log("notificate \'10-point-pr badge\'");
end

rule "20 point pr badge"
	salience -1000
when
    PointConcept(name == 'p+r', score >= 20.0)
    $bc : BadgeCollectionConcept(badgeEarned not contains '20-point-pr')
    Game( $gameId: id)
    Player( $playerId : id)
then
	log("apply \'20-point-pr badge\'");
	$bc.getBadgeEarned().add('20-point-pr');
	BadgeNotification notification = new BadgeNotification($gameId,$playerId,'20-point-pr');
	notificationSrv.notificate(notification);
	log("notificate \'20-point-pr badge\'");
end


rule "50 point pr badge"
	salience -1000
when
    PointConcept(name == 'p+r', score >= 50.0)
    $bc : BadgeCollectionConcept(badgeEarned not contains '50-point-pr')
    Game( $gameId: id)
    Player( $playerId : id)
then
	log("apply \'50-point-pr badge\'");
	$bc.getBadgeEarned().add('50-point-pr');
	BadgeNotification notification = new BadgeNotification($gameId,$playerId,'50-point-pr');
	notificationSrv.notificate(notification);
	log("notificate \'50-point-pr badge\'");
end

rule "100 point pr badge"
	salience -1000
when
    PointConcept(name == 'p+r', score >= 100.0)
    $bc : BadgeCollectionConcept(badgeEarned not contains '100-point-pr')
    Game( $gameId: id)
    Player( $playerId : id)
then
	log("apply \'100-point-pr badge\'");
	$bc.getBadgeEarned().add('100-point-pr');
	BadgeNotification notification = new BadgeNotification($gameId,$playerId,'100-point-pr');
	notificationSrv.notificate(notification);
	log("notificate \'100-point-pr badge\'");
end

rule "200 point pr badge"
	salience -1000
when
    PointConcept(name == 'p+r', score >= 200.0)
    $bc : BadgeCollectionConcept(badgeEarned not contains '200-point-pr')
    Game( $gameId: id)
    Player( $playerId : id)
then
	log("apply \'200-point-pr badge\'");
	$bc.getBadgeEarned().add('200-point-pr');
	BadgeNotification notification = new BadgeNotification($gameId,$playerId,'200-point-pr');
	notificationSrv.notificate(notification);
	log("notificate \'200-point-pr badge\'");
end