package eu.trentorise.game.model


rule "init point"
	salience 1000
when
    not PointConcept(name == "green leaves")
then
	log("apply \'init point\'");
	PointConcept pc = new PointConcept('green leaves');
	insert(pc);
end



rule "update bike/foot point"
	no-loop
when
    InputData( $bike : data["bikeDistance"])
    InputData( $walk : data["walkDistance"])
    $pc : PointConcept(name == "green leaves")
then
	log("apply \'update point\'");
	Integer dist = new Double((Double) $bike + (Double) $walk).intValue();
    $pc.setScore($pc.getScore() + 2.0 * dist);
    update($pc);
end
