package eu.trentorise.game.model


rule "init point"
	salience 1000
when
    not PointConcept(name == "green leaves")
then
	System.out.println("apply \'init point\'");
	PointConcept pc = new PointConcept('green leaves');
	insert(pc);
end



rule "update point"
	no-loop
when
    InputData( $d : data["bikeDistance"] > 1.0 )
    $pc : PointConcept(name == "green leaves")
then
	System.out.println("apply \'update point\'");
    $pc.setScore($pc.getScore() + 2.0);
    update($pc);
end


query "getGameConcepts"
    $result: GameConcept()
end
