FROM node:14 AS react-build
ARG  REACT_APP_API_ENDPOINT=http://localhost:8010/gamification
WORKDIR /app
COPY public /app/public
COPY src /app/src
COPY .env /app/
COPY package.json ./
COPY tsconfig.json ./
COPY .yarnrc /app/
COPY yarn.lock /app/yarn.lock
RUN yarn
RUN yarn build

FROM scratch
COPY --from=react-build /app/node_modules /node_modules