package eu.trentorise.game.model


rule "init customData"
when
    Action( $actionId: id == 'init-data')
    $cd : CustomData(this["counter"] == null)
then
	$cd.put("counter",1000);
	$cd.put("areas", new java.util.ArrayList<String>()); 
	update($cd);	
	log("Action: " + $actionId);
end

rule "edit counter"
when
    Action( id == 'edit-data')
    $cd : CustomData()
then
	Integer c = (Integer) $cd.get("counter");
	$cd.put("counter", c + 10);
end

rule "edit areas"
when
    Action( id == 'add-area')
    $cd : CustomData(this["areas"] != null, this["areas"] not contains 'area-51')
then
	java.util.List<String> areas = (java.util.List<String>) $cd.get("areas"); 
	areas.add('area-51');
	log('added area-51');
	update($cd);
end



