package eu.trentorise.game.model

/* ***************************************************************************
  INIT POINTS
  
*************************************************************************** */


rule "init green point"
	salience 1000
when
    not PointConcept(name == "green leaves")
then
	log("apply \'init green leaves points\'");
	PointConcept pc = new PointConcept('green leaves');
	insert(pc);
end

rule "init health point"
	salience 1000
when
    not PointConcept(name == "health")
then
	log("apply \'init health points\'");
	PointConcept pc = new PointConcept('health');
	insert(pc);
end


rule "init p+r point"
	salience 1000
when
    not PointConcept(name == "p+r")
then
	log("apply \'init p+r points\'");
	PointConcept pc = new PointConcept('p+r');
	insert(pc);
end

/* ***************************************************************************
  INIT BADGE COLLECTIONS
  
*************************************************************************** */

rule "init green badge collection"
	salience 1000
when
    not BadgeCollectionConcept(name == "green leaves")
then
	log("apply \'init green leaves badge collection\'");
	BadgeCollectionConcept bcc = new BadgeCollectionConcept("green leaves");
	insert(bcc);
end

rule "init health badge collection"
	salience 1000
when
    not BadgeCollectionConcept(name == "health")
then
	log("apply \'init health badge collection\'");
	BadgeCollectionConcept bcc = new BadgeCollectionConcept("health");
	insert(bcc);
end

rule "init p+r badge collection"
	salience 1000
when
    not BadgeCollectionConcept(name == "p+r")
then
	log("apply \'init p+r badge collection\'");
	BadgeCollectionConcept bcc = new BadgeCollectionConcept("p+r");
	insert(bcc);
end

rule "init special badge collection"
	salience 1000
when
    not BadgeCollectionConcept(name == "special")
then
	log("apply \'init special badge collection\'");
	BadgeCollectionConcept bcc = new BadgeCollectionConcept("special");
	insert(bcc);
end