/**
 * Copyright 2018-2019 SmartCommunity Lab(FBK-ICT).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

/*
 * Gamification Engine API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.smartcommunitylab.basic.api;

import java.util.List;

import org.junit.Ignore;
import org.junit.Test;

import it.smartcommunitylab.ApiException;
import it.smartcommunitylab.model.ArchivedConcept;

/**
 * API tests for ArchiveConceptControllerApi
 */
@Ignore
public class ArchiveConceptControllerApiTest {

    private final ArchiveConceptControllerApi api = new ArchiveConceptControllerApi();

    
    /**
     * Read archive concepts for a game with optional filter parameters
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void readArchivesForGameUsingGETTest() throws ApiException {
        String gameId = null;
        String playerId = null;
        String state = null;
        Long from = null;
        Long to = null;
        List<ArchivedConcept> response = api.readArchivesForGameUsingGET(gameId, playerId, state, from, to);

        // TODO: test validations
    }
    
}
