package eu.trentorise.game.model

import eu.trentorise.game.notification.BadgeNotification;

global Integer steps_leg_1;
global Integer steps_leg_2;
global Integer steps_leg_3;
global Integer steps_leg_4;
global Integer steps_leg_5;
global Integer steps_leg_6;
global Integer steps_leg_7;


rule "R-add-badge leg-1"
when 
    PointConcept(name == 'steps', score >= steps_leg_1)
    $bc : BadgeCollectionConcept(name =="Meano-FliessItinerary", badgeEarned not contains 'Fai della Paganella') 
    Game( $gameId: id)
    Player($teamId : id, team == true)
then
    log("apply \'R-add-badge leg-1\'");
    $bc.getBadgeEarned().add('Fai della Paganella');
    insert( new BadgeNotification($gameId,$teamId,'Fai della Paganella'));
    update( $bc );
end

rule "R-add-badge leg-2"
when 
    PointConcept(name == 'steps', score >= steps_leg_1 + steps_leg_2)
    $bc : BadgeCollectionConcept(name =="Meano-FliessItinerary", badgeEarned not contains 'Bolzano') 
    Game( $gameId: id)
    Player($teamId : id, team == true)
then
    log("apply \'R-add-badge leg-2\'");
    $bc.getBadgeEarned().add('Bolzano');
    insert( new BadgeNotification($gameId,$teamId,'Bolzano'));
    update( $bc );
end

rule "R-add-badge leg-3"
when 
    PointConcept(name == 'steps', score >= steps_leg_1 + steps_leg_2 + steps_leg_3)
    $bc : BadgeCollectionConcept(name =="Meano-FliessItinerary", badgeEarned not contains 'Merano') 
    Game( $gameId: id)
    Player($teamId : id, team == true)
then
    log("apply \'R-add-badge leg-3\'");
    $bc.getBadgeEarned().add('Merano');
    insert( new BadgeNotification($gameId,$teamId,'Merano'));
    update( $bc );
end

rule "R-add-badge leg-4"
when 
    PointConcept(name == 'steps', score >= steps_leg_1 + steps_leg_2 + steps_leg_3 + steps_leg_4)
    $bc : BadgeCollectionConcept(name =="Meano-FliessItinerary", badgeEarned not contains 'Prato allo Stelvio') 
    Game( $gameId: id)
    Player($teamId : id, team == true)
then
    log("apply \'R-add-badge leg-4\'");
    $bc.getBadgeEarned().add('Prato allo Stelvio');
    insert( new BadgeNotification($gameId,$teamId,'Prato allo Stelvio'));
    update( $bc );
end

rule "R-add-badge leg-5"
when 
    PointConcept(name == 'steps', score >= steps_leg_1 + steps_leg_2 + steps_leg_3 + steps_leg_4 + steps_leg_5)
    $bc : BadgeCollectionConcept(name =="Meano-FliessItinerary", badgeEarned not contains 'Curon Venosta') 
    Game( $gameId: id)
    Player($teamId : id, team == true)
then
    log("apply \'R-add-badge leg-5\'");
    $bc.getBadgeEarned().add('Curon Venosta');
    insert( new BadgeNotification($gameId,$teamId,'Curon Venosta'));
    update( $bc );
end

rule "R-add-badge leg-6"
when 
    PointConcept(name == 'steps', score >= steps_leg_1 + steps_leg_2 + steps_leg_3 + steps_leg_4 + steps_leg_5 + steps_leg_6)
    $bc : BadgeCollectionConcept(name =="Meano-FliessItinerary", badgeEarned not contains 'Hoch') 
    Game( $gameId: id)
    Player($teamId : id, team == true)
then
    log("apply \'R-add-badge leg-6\'");
    $bc.getBadgeEarned().add('Hoch');
    insert( new BadgeNotification($gameId,$teamId,'Hoch'));
    update( $bc );
end

rule "R-add-badge leg-7"
when 
    PointConcept(name == 'steps', score >= steps_leg_1 + steps_leg_2 + steps_leg_3 + steps_leg_4 + steps_leg_5 + steps_leg_6 + steps_leg_7)
    $bc : BadgeCollectionConcept(name =="Meano-FliessItinerary", badgeEarned not contains 'Fliess') 
    Game( $gameId: id)
    Player($teamId : id, team == true)
then
    log("apply \'R-add-badge leg-7\'");
    $bc.getBadgeEarned().add('Fliess');
    insert( new BadgeNotification($gameId,$teamId,'Fliess'));
    update( $bc );
end
