package it.smartcommunitylab.gamification.log2elastic;

public enum RecordType {
	ACTION, RULE_POINTCONCEPT, RULE_BADGECOLLECTIONCONCEPT, CLASSIFICATION, CHALLENGEASSIGNED, CHALLENGECOMPLETE, USERCREATION
}
