
package eu.trentorise.game.model


import eu.trentorise.game.notification.BadgeNotification
import java.util.Set
import java.util.HashSet


rule "002-turtle"
    salience -1000
when
    PointConcept(name == "total", score >= 50)
    $bc : BadgeCollectionConcept(name == "totalBadge", badgeEarned not contains "002-turtle")
    Game( $gameId: id)
    Player( $playerId : id)
then
    log("apply '002-turtle badge'");
    $bc.getBadgeEarned().add("002-turtle");
    insert( new BadgeNotification($gameId,$playerId,"002-turtle"));
    update( $bc );
end
        