package eu.trentorise.game.model

global Integer walk_min;
global Integer bike_min;
global Integer train_max;

rule "update walk counters"
lock-on-active
when
    InputData( $km : data["walkDistance"] != null, $km >= walk_min)
    $c : CustomData($counterKm : this["walk-km"], $counterTrips: this["walk-trips"])
then
	if($counterKm == null) {
		$c.put("walk-km", (Double) $km);
	} else {
		$c.put("walk-km", (Double) $counterKm + (Double) $km);
	}
	if($counterTrips == null) {
		$c.put("walk-trips", 1);
	} else {
		$c.put("walk-trips", (Integer) $counterTrips + 1);
	}
    update($c);
end


rule "update bike counters"
lock-on-active
when
    InputData( $km : data["bikeDistance"] != null, $km >= bike_min)
    $c : CustomData($counterKm : this["bike-km"], $counterTrips : this["bike-trips"])
then
	if($counterKm == null) {
		$c.put("bike-km", (Double) $km);
	} else {
		$c.put("bike-km", (Double) $counterKm + (Double) $km);
	}
	if($counterTrips == null) {
		$c.put("bike-trips", 1);
	} else {
		$c.put("bike-trips", (Integer) $counterTrips + 1);
	}
    update($c);
end


rule "update bikesharing counters"
lock-on-active
when
    InputData( $km : data["bikeDistance"] != null, data["bikesharing"] == true, $km >= bike_min)
    $c : CustomData($counterKm : this["bikesharing-km"], $counterTrips : this["bikesharing-trips"])
then
	if($counterKm == null) {
		$c.put("bikesharing-km", (Double) $km);
	} else {
		$c.put("bikesharing-km", (Double) $counterKm + (Double) $km);
	}
	if($counterTrips == null) {
		$c.put("bikesharing-trips", 1);
	} else {
		$c.put("bikesharing-trips", (Integer) $counterTrips + 1);
	}
    update($c);
end


rule "update bus counters"
lock-on-active
when
    InputData( $km : data["busDistance"] != null)
    $c : CustomData($counterKm : this["bus-km"], $counterTrips : this["bus-trips"])
then
	if($counterKm == null) {
		$c.put("bus-km", (Double) $km);
	} else {
		$c.put("bus-km", (Double) $counterKm + (Double) $km);
	}
	if($counterTrips == null) {
		$c.put("bus-trips", 1);
	} else {
		$c.put("bus-trips", (Integer) $counterTrips + 1);
	}
    update($c);
end


rule "update train counters"
lock-on-active
when
    InputData( $km : data["trainDistance"] != null)
    $c : CustomData($counterKm : this["train-km"], $counterTrips : this["train-trips"])
then
	if($counterKm == null) {
		$c.put("train-km", (Double) $km);
	} else {
		$c.put("train-km", (Double) $counterKm + (Double) $km);
	}
	if($counterTrips == null) {
		$c.put("train-trips", 1);
	} else {
		$c.put("train-trips", (Integer) $counterTrips + 1);
	}
    update($c);
end

rule "update car counters"
lock-on-active
when
    InputData( $km : data["carDistance"] != null)
    $c : CustomData($counterKm : this["car-km"],$counterTrips : this["car-trips"])
then
	if($counterKm == null) {
		$c.put("car-km", (Double) $km);
	} else {
		$c.put("car-km", (Double) $counterKm + (Double) $km);
	}
	if($counterTrips == null) {
		$c.put("car-trips", 1);
	} else {
		$c.put("car-trips", (Integer) $counterTrips + 1);
	}
    update($c);
end
