package eu.trentorise.game.model

import eu.trentorise.game.model.core.GameConcept
import eu.trentorise.game.model.core.Notification

import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import eu.trentorise.game.managers.DroolsEngine;

// ***************************************** queries 

query "getGameConcepts"
	$result: GameConcept()
end

query "getNotifications"
	$notifications: Notification()
end

query "getCustomData"
	$data: CustomData()
end

query "getUpdateTeam"
	$data: UpdateTeam()
end

query "getUpdateMembers"
	$data: UpdateMembers()
end

// ****************************************** global functions 	

function void log(String msg) {
	Logger logger = LoggerFactory.getLogger(DroolsEngine.class);
	logger.info(msg);
}