package eu.trentorise.game.model

//list any import classes here.
import eu.trentorise.game.core.Utility;

//declare any global variables here
global Utility utils;

rule 'ch_next_badge_check'
	salience -3000
when
	$challenge : ChallengeConcept( modelName == "nextBadge", $target: fields["target"] != null, $bonusPointType : fields["bonusPointType"], $bonusScore : fields["bonusScore"], $bcName : fields["badgeCollectionName"], $counter: fields["initialBadgeNum"], isCompleted() != true )
	$bc : BadgeCollectionConcept(name == $bcName, $badges : badgeEarned, badgeEarned.size() >= $target + $counter)
	$pc : PointConcept(name == (String) $bonusPointType)
then
	utils.log('nextBadge COMPLETED');
	$challenge.completed();
	$pc.setScore($pc.getScore() + (Double) $bonusScore);
	update($pc);
	update($challenge);	
end