package eu.trentorise.game.model

import eu.trentorise.game.notification.BadgeNotification;
import eu.trentorise.game.core.Utility;

//declare any global variables here
global Utility utils;
global java.util.ArrayList parkings;

/* ***************************************************************************
BIKE AFICIONADO COLLECTION  
*************************************************************************** */
rule "1 trip bike"
	salience -1000
when
	PointConcept(name == 'Bike_Trips', score >= 1.0)
    $bc : BadgeCollectionConcept(name == "bike aficionado", badgeEarned not contains '1_bike_trip')
    Game( $gameId: id)
    Player( $playerId : id)
then
	utils.log("apply \'1_bike_trip badge\'");
	$bc.getBadgeEarned().add('1_bike_trip');
	insert( new BadgeNotification($gameId,$playerId,"bike aficionado",'1_bike_trip'));
	insert ( new BadgeUpdate("1_bike_trip", "bike aficionado"));
	update( $bc );
end


rule "5 trip bike"
	salience -1000
when
	PointConcept(name == 'Bike_Trips', score >= 5.0)
    $bc : BadgeCollectionConcept(name == "bike aficionado", badgeEarned not contains '5_bike_trip')
    Game( $gameId: id)
    Player( $playerId : id)
then	
	utils.log("apply \'5_bike_trip badge\'");
	$bc.getBadgeEarned().add('5_bike_trip');
	insert( new BadgeNotification($gameId,$playerId,"bike aficionado",'5_bike_trip'));
	insert ( new BadgeUpdate("5_bike_trip", "bike aficionado"));
	update( $bc );
end


rule "10 trip bike"
	salience -1000
when
	PointConcept(name == 'Bike_Trips', score >= 10.0)
    $bc : BadgeCollectionConcept(name == "bike aficionado", badgeEarned not contains '10_bike_trip')
    Game( $gameId: id)
    Player( $playerId : id)
then
	utils.log("apply \'10_bike_trip badge\'");
	$bc.getBadgeEarned().add('10_bike_trip');
	insert( new BadgeNotification($gameId,$playerId,"bike aficionado",'10_bike_trip'));
	insert ( new BadgeUpdate("10_bike_trip", "bike aficionado"));
	update( $bc );
end


rule "25 trip bike"
	salience -1000
when
	PointConcept(name == 'Bike_Trips', score >= 25.0)
    $bc : BadgeCollectionConcept(name == "bike aficionado", badgeEarned not contains '25_bike_trip')
    Game( $gameId: id)
    Player( $playerId : id)
then
	utils.log("apply \'25_bike_trip badge\'");
	$bc.getBadgeEarned().add('25_bike_trip');
	insert( new BadgeNotification($gameId,$playerId,"bike aficionado",'25_bike_trip'));
	insert ( new BadgeUpdate("25_bike_trip", "bike aficionado"));
	update( $bc );
end


rule "50 trip bike"
	salience -1000
when
	PointConcept(name == 'Bike_Trips', score >= 50.0)
    $bc : BadgeCollectionConcept(name == "bike aficionado", badgeEarned not contains '50_bike_trip')
    Game( $gameId: id)
    Player( $playerId : id)
then
	utils.log("apply \'50_bike_trip badge\'");
	$bc.getBadgeEarned().add('50_bike_trip');
	insert( new BadgeNotification($gameId,$playerId,"bike aficionado",'50_bike_trip'));
	insert ( new BadgeUpdate("50_bike_trip", "bike aficionado"));
	update( $bc );
end

rule "100 trip bike"
	salience -1000
when
	PointConcept(name == 'Bike_Trips', score >= 100.0)
    $bc : BadgeCollectionConcept(name == "bike aficionado", badgeEarned not contains '100_bike_trip')
    Game( $gameId: id)
    Player( $playerId : id)
then
	utils.log("apply \'100_bike_trip badge\'");
	$bc.getBadgeEarned().add('100_bike_trip');
	insert( new BadgeNotification($gameId,$playerId,"bike aficionado",'100_bike_trip'));
	insert ( new BadgeUpdate("100_bike_trip", "bike aficionado"));
	update( $bc );
end

rule "200 trip bike"
	salience -1000
when
	PointConcept(name == 'Bike_Trips', score >= 200.0)
    $bc : BadgeCollectionConcept(name == "bike aficionado", badgeEarned not contains '200_bike_trip')
    Game( $gameId: id)
    Player( $playerId : id)
then
	utils.log("apply \'200_bike_trip badge\'");
	$bc.getBadgeEarned().add('200_bike_trip');
	insert( new BadgeNotification($gameId,$playerId,"bike aficionado",'200_bike_trip'));
	insert ( new BadgeUpdate("200_bike_trip", "bike aficionado"));
	update( $bc );
end

rule "500 trip bike"
	salience -1000
when
	PointConcept(name == 'Bike_Trips', score >= 500.0)
    $bc : BadgeCollectionConcept(name == "bike aficionado", badgeEarned not contains '500_bike_trip')
    Game( $gameId: id)
    Player( $playerId : id)
then
	utils.log("apply \'500_bike_trip badge\'");
	$bc.getBadgeEarned().add('500_bike_trip');
	insert( new BadgeNotification($gameId,$playerId,"bike aficionado",'500_bike_trip'));
	insert ( new BadgeUpdate("500_bike_trip", "bike aficionado"));
	update( $bc );
end

/* ***************************************************************************
BIKE SHARING PIONEER COLLECTION  
*************************************************************************** */
rule "bike sharing pioneer badge start"
	salience -1000
when
    InputData( $startBS : data['startBike'] != null)
    $bc : BadgeCollectionConcept(name == "bike sharing pioneer", badgeEarned not contains ($startBS+'_BSstation'))
    Game( $gameId: id)
    Player( $playerId : id)
then
	utils.log("apply  \'"+$startBS+"_BSstation badge\'");
	$bc.getBadgeEarned().add((String) $startBS+'_BSstation');
	insert( new BadgeNotification($gameId,$playerId,"bike sharing pioneer",$startBS+'_BSstation'));
	insert ( new BadgeUpdate((String) $startBS+"_BSstation", "bike sharing pioneer"));	
	update( $bc );
end


rule "bike sharing pioneer badge end"
	salience -1000
when
    InputData( $endBS : data['endBike'] != null)
    $bc : BadgeCollectionConcept(name == "bike sharing pioneer", badgeEarned not contains ($endBS+'_BSstation'))
    Game( $gameId: id)
    Player( $playerId : id)
then
	utils.log("apply  \'"+$endBS+"_BSstation badge\'");
	$bc.getBadgeEarned().add((String) $endBS+'_BSstation');
	insert( new BadgeNotification($gameId,$playerId,"bike sharing pioneer",$endBS+'_BSstation'));
	insert ( new BadgeUpdate((String) $endBS+"_BSstation", "bike sharing pioneer"));		
	update( $bc );
end


/* ***************************************************************************
PUBLIC TRANSPORT AFICIONADO COLLECTION
*************************************************************************** */

rule "5 trip public transport"
	salience -1000
when
    $bc : BadgeCollectionConcept(name == "public transport aficionado", badgeEarned not contains '5_pt_trip')
    $busTrips : PointConcept(name == "Bus_Trips")
    $trainTrips : PointConcept(name == "Train_Trips")
    Game( $gameId: id)
    Player( $playerId : id)
then
	if ($busTrips.getScore() + $trainTrips.getScore() >= 5.0d) {
		utils.log("apply \'5_pt_trip badge\'");
		$bc.getBadgeEarned().add('5_pt_trip');
		insert( new BadgeNotification($gameId,$playerId,"public transport aficionado",'5_pt_trip'));
		insert( new BadgeUpdate("5_pt_trip", "public transport aficionado"));	
		update( $bc );
	}
end


rule "10 trip public transport"
	salience -1000
when
	$bc : BadgeCollectionConcept(name == "public transport aficionado", badgeEarned not contains '10_pt_trip')
    $busTrips : PointConcept(name == "Bus_Trips")
    $trainTrips : PointConcept(name == "Train_Trips")
    Game( $gameId: id)
    Player( $playerId : id)
then
	if ($busTrips.getScore() + $trainTrips.getScore() >= 10.0d) {
		utils.log("apply \'10_pt_trip badge\'");
		$bc.getBadgeEarned().add('10_pt_trip');
		insert( new BadgeNotification($gameId,$playerId,"public transport aficionado",'10_pt_trip'));
		insert( new BadgeUpdate("10_pt_trip", "public transport aficionado"));	
		update( $bc );
	}
end

rule "25 trip public transport"
	salience -1000
when
    $bc : BadgeCollectionConcept(name == "public transport aficionado", badgeEarned not contains '25_pt_trip')
    $busTrips : PointConcept(name == "Bus_Trips")
    $trainTrips : PointConcept(name == "Train_Trips")
    Game( $gameId: id)
    Player( $playerId : id)
then
	if ($busTrips.getScore() + $trainTrips.getScore() >= 25.0d) {
		utils.log("apply \'25_pt_trip badge\'");
		$bc.getBadgeEarned().add('25_pt_trip');
		insert( new BadgeNotification($gameId,$playerId,"public transport aficionado",'25_pt_trip'));
		insert( new BadgeUpdate("25_pt_trip", "public transport aficionado"));	
		update( $bc );
	}
end

rule "50 trip public transport"
	salience -1000
when
    $bc : BadgeCollectionConcept(name == "public transport aficionado", badgeEarned not contains '50_pt_trip')
    $busTrips : PointConcept(name == "Bus_Trips")
    $trainTrips : PointConcept(name == "Train_Trips")
    Game( $gameId: id)
    Player( $playerId : id)
then
	if ($busTrips.getScore() + $trainTrips.getScore() >= 50.0d) {
		utils.log("apply \'50_pt_trip badge\'");
		$bc.getBadgeEarned().add('50_pt_trip');
		insert( new BadgeNotification($gameId,$playerId,"public transport aficionado",'50_pt_trip'));
		insert( new BadgeUpdate("50_pt_trip", "public transport aficionado"));	
		update( $bc );
	}
end

rule "100 trip public transport"
	salience -1000
when
    $bc : BadgeCollectionConcept(name == "public transport aficionado", badgeEarned not contains '100_pt_trip')
    $busTrips : PointConcept(name == "Bus_Trips")
    $trainTrips : PointConcept(name == "Train_Trips")
    Game( $gameId: id)
    Player( $playerId : id)
then
	if ($busTrips.getScore() + $trainTrips.getScore() >= 100.0d) {
		utils.log("apply \'100_pt_trip badge\'");
		$bc.getBadgeEarned().add('100_pt_trip');
		insert( new BadgeNotification($gameId,$playerId,"public transport aficionado",'100_pt_trip'));
		insert( new BadgeUpdate("100_pt_trip", "public transport aficionado"));	
		update( $bc );
	}
end

rule "200 trip public transport"
	salience -1000
when
    $bc : BadgeCollectionConcept(name == "public transport aficionado", badgeEarned not contains '200_pt_trip')
    $busTrips : PointConcept(name == "Bus_Trips")
    $trainTrips : PointConcept(name == "Train_Trips")
    Game( $gameId: id)
    Player( $playerId : id)
then
	if ($busTrips.getScore() + $trainTrips.getScore() >= 200.0d) {
		utils.log("apply \'200_pt_trip badge\'");
		$bc.getBadgeEarned().add('200_pt_trip');
		insert( new BadgeNotification($gameId,$playerId,"public transport aficionado",'200_pt_trip'));
		insert( new BadgeUpdate("200_pt_trip", "public transport aficionado"));	
		update( $bc );
	}
end

rule "500 trip public transport"
	salience -1000
when
    $bc : BadgeCollectionConcept(name == "public transport aficionado", badgeEarned not contains '500_pt_trip')
    $busTrips : PointConcept(name == "Bus_Trips")
    $trainTrips : PointConcept(name == "Train_Trips")
    Game( $gameId: id)
    Player( $playerId : id)
then
	if ($busTrips.getScore() + $trainTrips.getScore() >= 500.0d) {
		utils.log("apply \'500_pt_trip badge\'");
		$bc.getBadgeEarned().add('500_pt_trip');
		insert( new BadgeNotification($gameId,$playerId,"public transport aficionado",'500_pt_trip'));
		insert( new BadgeUpdate("500_pt_trip", "public transport aficionado"));	
		update( $bc );
	}
end


/* ***************************************************************************
PARK & RIDE PIONEER COLLECTION 
*************************************************************************** */  

rule "park badge"
	salience -1000
when
    InputData( $park : data['park'] != null, parkings.contains((String)$park) )
    $bc : BadgeCollectionConcept(name == "park and ride pioneer", badgeEarned not contains ($park+'_parking'))
    Game( $gameId: id)
    Player( $playerId : id)
then
	utils.log("apply  \'"+$park+"_parking badge\'");
	$bc.getBadgeEarned().add((String) $park+'_parking');
	insert( new BadgeNotification($gameId,$playerId,"park and ride pioneer",$park+'_parking'));
	insert ( new BadgeUpdate((String) $park+"_parking", "park and ride pioneer"));		
	update( $bc );
end


/* ***************************************************************************
IMPACT 0 COLLECTION
*************************************************************************** */ 
rule "1 trip impact0"
	salience -1000
when
    $bc : BadgeCollectionConcept(name == "sustainable life", badgeEarned not contains '1_zero_impact_trip')
    $zeroImpact : PointConcept(name == "ZeroImpact_Trips")
    Game( $gameId: id)
    Player( $playerId : id)
then
	if ($zeroImpact.getScore() >= 1.0d) {
		utils.log("apply \'1_zero_impact_trip\'");
		$bc.getBadgeEarned().add('1_zero_impact_trip');
		insert( new BadgeNotification($gameId,$playerId,"sustainable life",'1_zero_impact_trip'));
		insert( new BadgeUpdate("1_zero_impact_trip", "sustainable life"));	
		update( $bc );
	}
end


rule "5 trip impact0"
	salience -1000
when
    $bc : BadgeCollectionConcept(name == "sustainable life", badgeEarned not contains '5_zero_impact_trip')
    $zeroImpact : PointConcept(name == "ZeroImpact_Trips")
    Game( $gameId: id)
    Player( $playerId : id)
then
	if ($zeroImpact.getScore() >= 5.0d) {
		utils.log("apply \'5_zero_impact_trip\'");
		$bc.getBadgeEarned().add('5_zero_impact_trip');
		insert( new BadgeNotification($gameId,$playerId,"sustainable life",'5_zero_impact_trip'));
		insert( new BadgeUpdate("5_zero_impact_trip", "sustainable life"));	
		update( $bc );
	}
end


rule "10 trip impact0"
	salience -1000
when
    $bc : BadgeCollectionConcept(name == "sustainable life", badgeEarned not contains '10_zero_impact_trip')
    $zeroImpact : PointConcept(name == "ZeroImpact_Trips")
    Game( $gameId: id)
    Player( $playerId : id)
then
	if ($zeroImpact.getScore() >= 10.0d) {
		utils.log("apply \'10_zero_impact_trip\'");
		$bc.getBadgeEarned().add('10_zero_impact_trip');
		insert( new BadgeNotification($gameId,$playerId,"sustainable life",'10_zero_impact_trip'));
		insert( new BadgeUpdate("10_zero_impact_trip", "sustainable life"));	
		update( $bc );
	}
end

rule "25 trip impact0"
	salience -1000
when
    $bc : BadgeCollectionConcept(name == "sustainable life", badgeEarned not contains '25_zero_impact_trip')
    $zeroImpact : PointConcept(name == "ZeroImpact_Trips")
    Game( $gameId: id)
    Player( $playerId : id)
then
	if ($zeroImpact.getScore() >= 25.0d) {
		utils.log("apply \'25_zero_impact_trip\'");
		$bc.getBadgeEarned().add('25_zero_impact_trip');
		insert( new BadgeNotification($gameId,$playerId,"sustainable life",'25_zero_impact_trip'));
		insert( new BadgeUpdate("25_zero_impact_trip", "sustainable life"));	
		update( $bc );
	}
end


rule "50 trip impact0"
	salience -1000
when
    $bc : BadgeCollectionConcept(name == "sustainable life", badgeEarned not contains '50_zero_impact_trip')
    $zeroImpact : PointConcept(name == "ZeroImpact_Trips")
    Game( $gameId: id)
    Player( $playerId : id)
then
	if ($zeroImpact.getScore() >= 50.0d) {
		utils.log("apply \'50_zero_impact_trip\'");
		$bc.getBadgeEarned().add('50_zero_impact_trip');
		insert( new BadgeNotification($gameId,$playerId,"sustainable life",'50_zero_impact_trip'));
		insert( new BadgeUpdate("50_zero_impact_trip", "sustainable life"));	
		update( $bc );
	}
end

rule "100 trip impact0"
	salience -1000
when
    $bc : BadgeCollectionConcept(name == "sustainable life", badgeEarned not contains '100_zero_impact_trip')
    $zeroImpact : PointConcept(name == "ZeroImpact_Trips")
    Game( $gameId: id)
    Player( $playerId : id)
then
	if ($zeroImpact.getScore() >= 100.0d) {
		utils.log("apply \'100_zero_impact_trip\'");
		$bc.getBadgeEarned().add('100_zero_impact_trip');
		insert( new BadgeNotification($gameId,$playerId,"sustainable life",'100_zero_impact_trip'));
		insert( new BadgeUpdate("100_zero_impact_trip", "sustainable life"));	
		update( $bc );
	}
end

rule "200 trip impact0"
	salience -1000
when
    $bc : BadgeCollectionConcept(name == "sustainable life", badgeEarned not contains '200_zero_impact_trip')
    $zeroImpact : PointConcept(name == "ZeroImpact_Trips")
    Game( $gameId: id)
    Player( $playerId : id)
then
	if ($zeroImpact.getScore() >= 200.0d) {
		utils.log("apply \'200_zero_impact_trip\'");
		$bc.getBadgeEarned().add('200_zero_impact_trip');
		insert( new BadgeNotification($gameId,$playerId,"sustainable life",'200_zero_impact_trip'));
		insert( new BadgeUpdate("200_zero_impact_trip", "sustainable life"));	
		update( $bc );
	}
end

rule "500 trip impact0"
	salience -1000
when
    $bc : BadgeCollectionConcept(name == "sustainable life", badgeEarned not contains '500_zero_impact_trip')
    $zeroImpact : PointConcept(name == "ZeroImpact_Trips")
    Game( $gameId: id)
    Player( $playerId : id)
then
	if ($zeroImpact.getScore() >= 500.0d) {
		utils.log("apply \'500_zero_impact_trip\'");
		$bc.getBadgeEarned().add('500_zero_impact_trip');
		insert( new BadgeNotification($gameId,$playerId,"sustainable life",'500_zero_impact_trip'));
		insert( new BadgeUpdate("500_zero_impact_trip", "sustainable life"));	
		update( $bc );
	}
end

/* ***************************************************************************
APP RECOMMENDATION COLLECTION
*************************************************************************** */ 

rule "3 recommendations"
	salience -1000
when
    $bc : BadgeCollectionConcept(name == "recommendations", badgeEarned not contains '3_recommendations')
    $reccom : PointConcept(name == "Recommendations")
    $pc : PointConcept(name == "green leaves")
    Game( $gameId: id)
    Player( $playerId : id)
then
	if ($reccom.getScore() >= 3.0d) {
		utils.log("apply \'3_recommendations badge\'");
		$bc.getBadgeEarned().add('3_recommendations');
		insert( new BadgeNotification($gameId,$playerId,"recommendations",'3_recommendations'));
		insert( new BadgeUpdate("3_recommendations", "recommendations"));	
		update( $bc );
		$pc.setScore($pc.getScore() + 50.0d);
    	update($pc);
	}
end

rule "5 recommendations"
	salience -1000
when
    $bc : BadgeCollectionConcept(name == "recommendations", badgeEarned not contains '5_recommendations')
    $reccom : PointConcept(name == "Recommendations")
    $pc : PointConcept(name == "green leaves")
    Game( $gameId: id)
    Player( $playerId : id)
then
	if ($reccom.getScore() >= 5.0d) {
		utils.log("apply \'5_recommendations badge\'");
		$bc.getBadgeEarned().add('5_recommendations');
		insert( new BadgeNotification($gameId,$playerId,"recommendations",'5_recommendations'));
		insert( new BadgeUpdate("5_recommendations", "recommendations"));	
		update( $bc );
		$pc.setScore($pc.getScore() + 100.0d);
    	update($pc); 
	}
end

rule "10 recommendations"
	salience -1000
when
    $bc : BadgeCollectionConcept(name == "recommendations", badgeEarned not contains '10_recommendations')
    $reccom : PointConcept(name == "Recommendations")
    $pc : PointConcept(name == "green leaves")
    Game( $gameId: id)
    Player( $playerId : id)
then
	if ($reccom.getScore() >= 10.0d) {
		utils.log("apply \'10_recommendations badge\'");
		$bc.getBadgeEarned().add('10_recommendations');
		insert( new BadgeNotification($gameId,$playerId,"recommendations",'10_recommendations'));
		insert( new BadgeUpdate("10_recommendations", "recommendations"));	
		update( $bc );;
		$pc.setScore($pc.getScore() + 200.0d);
    	update($pc);
	}
end

rule "25 recommendations"
	salience -1000
when
    $bc : BadgeCollectionConcept(name == "recommendations", badgeEarned not contains '25_recommendations')
    $reccom : PointConcept(name == "Recommendations")
    $pc : PointConcept(name == "green leaves")
    Game( $gameId: id)
    Player( $playerId : id)
then
	if ($reccom.getScore() >= 25.0d) {
		utils.log("apply \'25_recommendations badge\'");
		$bc.getBadgeEarned().add('25_recommendations');
		insert( new BadgeNotification($gameId,$playerId,"recommendations",'25_recommendations'));
		insert( new BadgeUpdate("25_recommendations", "recommendations"));	
		update( $bc );
		$pc.setScore($pc.getScore() + 300.0d);
    	update($pc);
	}
end