package eu.trentorise.game.model

import eu.trentorise.game.notification.BadgeNotification;
import eu.trentorise.game.task.Classification;
import eu.trentorise.game.core.Utility;

//declare any global variables here
global Utility utils;


/* ***************************************************************************
GREEN WEEK CLASSIFICATION
  
*************************************************************************** */

rule "1st of the week"
no-loop
	salience -1000
when
    Classification( name == 'week classification green', position == 1)
    Game( $gameId: id)
    Player( $playerId : id)
    $bc : BadgeCollectionConcept(name == "leaderboard top 3")
    $pc : PointConcept(name == "green leaves", $score : score, getPeriodCurrentScore("weekly") >= 0)
then
	utils.log("apply \'1st_of_the_week\'");
	if (! $bc.getBadgeEarned().contains("1st_of_the_week")) {
		$bc.getBadgeEarned().add('1st_of_the_week');
		update( $bc );
	}
	insert( new BadgeNotification($gameId,$playerId,"leaderboard top 3",'1st_of_the_week'));	
end

rule "2nd of the week"
no-loop
	salience -1000
when
    Classification( name == 'week classification green', position == 2)
    Game( $gameId: id)
    Player( $playerId : id)
    $bc : BadgeCollectionConcept(name == "leaderboard top 3")
    $pc : PointConcept(name == "green leaves", $score : score, getPeriodCurrentScore("weekly") >= 0)
then
	utils.log("apply \'2nd_of_the_week\'");
	if (! $bc.getBadgeEarned().contains("2nd_of_the_week")) {
		$bc.getBadgeEarned().add('2nd_of_the_week');
		update( $bc );
	}
	insert( new BadgeNotification($gameId,$playerId,"leaderboard top 3",'2nd_of_the_week'));
end

rule "3rd of the week"
no-loop
	salience -1000
when
    Classification( name == 'week classification green', position == 3)
    Game( $gameId: id)
    Player( $playerId : id)
    $bc : BadgeCollectionConcept(name == "leaderboard top 3")
    $pc : PointConcept(name == "green leaves", $score : score, getPeriodCurrentScore("weekly") >= 0)
then
	utils.log("apply \'3rd_of_the_week\'");
	if (! $bc.getBadgeEarned().contains("3rd_of_the_week")) {
		$bc.getBadgeEarned().add('3rd_of_the_week');
		update( $bc );
	}
	insert( new BadgeNotification($gameId,$playerId,"leaderboard top 3",'3rd_of_the_week'));
end